# Generated by Django 6.0.4 on 2026-06-04 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0005_subtransactiontype_payment_term_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardInventoryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_tag', to='purchase.itemmasterpurchase', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Dashboard Inventory Tag',
                'verbose_name_plural': 'Dashboard Inventory Tags',
                'ordering': ['item__nama'],
            },
        ),
    ]
