# Generated by Django 6.0.4 on 2026-06-06 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('entitas_bisnis', '0002_is_company_profile'),
        ('purchase', '0005_subtransactiontype_payment_term_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardinventorytag',
            name='entitas_bisnis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_inventory_tags', to='entitas_bisnis.entitasbisnis', verbose_name='Entitas Bisnis'),
        ),
        migrations.AlterField(
            model_name='dashboardinventorytag',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_tags', to='purchase.itemmasterpurchase', verbose_name='Item'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardinventorytag',
            unique_together={('item', 'entitas_bisnis')},
        ),
    ]
