# Generated by Django 6.0.6 on 2026-07-22 20:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitas_bisnis', '0003_add_standar_akuntansi'),
        ('purchase', '0010_purchaseitem_input_qty_purchaseitem_input_uom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('min_selections', models.IntegerField(default=0)),
                ('max_selections', models.IntegerField(default=1)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModifierOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('additional_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='catalog/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='entitas_bisnis.entitasbisnis')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_entries', to='purchase.itemmasterpurchase')),
            ],
            options={
                'verbose_name': 'Catalog Item',
                'verbose_name_plural': 'Catalog Items',
                'ordering': ['display_order', 'item__nama'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pos_catalog.catalogitem')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catalog Item Log',
                'verbose_name_plural': 'Catalog Item Logs',
                'ordering': ['-changed_at'],
            },
        ),
    ]
