# Generated by Django 6.0.4 on 2026-05-06 20:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos_config', '0001_initial'),
        ('purchase', '0003_add_nilai_residu_to_item_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('min_selections', models.IntegerField(default=0)),
                ('max_selections', models.IntegerField(default=1)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('merchant_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='pos_config.merchantposconfig')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModifierOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('additional_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='pos_catalog.modifiergroup')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='POSCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#0054a6', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('merchant_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='pos_config.merchantposconfig')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='POSProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pos/products/')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_available', models.BooleanField(default=True)),
                ('track_inventory', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pos_catalog.poscategory')),
                ('item_master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos_product', to='purchase.itemmasterpurchase')),
                ('merchant_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pos_config.merchantposconfig')),
            ],
            options={
                'ordering': ['display_order', 'pos_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0)),
                ('modifier_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='pos_catalog.modifiergroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_links', to='pos_catalog.posproduct')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('product', 'modifier_group')},
            },
        ),
        migrations.CreateModel(
            name='ProductStoreAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('selling_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_availability', to='pos_catalog.posproduct')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_availability', to='pos_config.storeposconfig')),
            ],
            options={
                'unique_together': {('product', 'store')},
            },
        ),
    ]
