# Generated by Django 6.0.6 on 2026-07-22 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos_catalog', '0001_initial'),
        ('pos_config', '0001_initial'),
        ('purchase', '0010_purchaseitem_input_qty_purchaseitem_input_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiergroup',
            name='merchant_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='pos_config.merchantposconfig'),
        ),
        migrations.AddField(
            model_name='modifieroption',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='pos_catalog.modifiergroup'),
        ),
        migrations.AddField(
            model_name='productmodifiergroup',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_links', to='purchase.itemmasterpurchase'),
        ),
        migrations.AddField(
            model_name='productmodifiergroup',
            name='modifier_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='pos_catalog.modifiergroup'),
        ),
        migrations.AlterUniqueTogether(
            name='catalogitem',
            unique_together={('entitas_bisnis', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='productmodifiergroup',
            unique_together={('item', 'modifier_group')},
        ),
    ]
