# Generated by Django 6.0.4 on 2026-06-05 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0002_is_company_profile'),
        ('pos_catalog', '0002_remove_pos_product_models'),
        ('purchase', '0005_subtransactiontype_payment_term_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='catalog/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='entitas_bisnis.entitasbisnis')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_entries', to='purchase.itemmasterpurchase')),
            ],
            options={
                'verbose_name': 'Catalog Item',
                'verbose_name_plural': 'Catalog Items',
                'ordering': ['display_order', 'item__nama'],
                'unique_together': {('entitas_bisnis', 'item')},
            },
        ),
        migrations.CreateModel(
            name='CatalogItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pos_catalog.catalogitem')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catalog Item Log',
                'verbose_name_plural': 'Catalog Item Logs',
                'ordering': ['-changed_at'],
            },
        ),
    ]
