# Generated by Django 6.0.4 on 2026-04-10 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitas_bisnis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('satuan', models.CharField(blank=True, max_length=50)),
                ('harga_pokok', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
            ],
            options={
                'verbose_name': 'Item Master',
                'verbose_name_plural': 'Item Master',
            },
        ),
        migrations.CreateModel(
            name='SalesHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_invoice', models.CharField(max_length=100, unique=True)),
                ('tanggal_transaksi', models.DateField()),
                ('termin_pembayaran', models.CharField(blank=True, max_length=50)),
                ('status_pengiriman', models.CharField(blank=True, choices=[('pending', 'Pending'), ('dikirim', 'Dikirim'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], max_length=50)),
                ('total_nilai', models.DecimalField(decimal_places=4, max_digits=19)),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_headers', to='entitas_bisnis.entitasbisnis')),
            ],
            options={
                'verbose_name': 'Sales Header',
                'verbose_name_plural': 'Sales Header',
            },
        ),
        migrations.CreateModel(
            name='SalesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuantitas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_satuan', models.DecimalField(decimal_places=4, max_digits=19)),
                ('diskon_persen', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('item_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_details', to='sales.itemmaster')),
                ('sales_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.salesheader')),
            ],
            options={
                'verbose_name': 'Sales Detail',
                'verbose_name_plural': 'Sales Detail',
            },
        ),
    ]
