# Generated by Django 6.0.4
# Noop migration kept to satisfy external dependency from jurnal app.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = []
