# Generated by Django 6.0.4 on 2026-04-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0003_cabangentitasbisnis_idx_cab_entitas_aktif_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesheader',
            options={'ordering': ['-tanggal_transaksi'], 'verbose_name': 'Sales Header', 'verbose_name_plural': 'Sales Header'},
        ),
        migrations.AlterField(
            model_name='salesheader',
            name='status_pengiriman',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('dikirim', 'Dikirim'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='salesheader',
            name='tanggal_transaksi',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='salesdetail',
            index=models.Index(fields=['sales_header', 'item_master'], name='idx_sd_header_item'),
        ),
        migrations.AddIndex(
            model_name='salesdetail',
            index=models.Index(fields=['item_master'], name='idx_sd_item'),
        ),
        migrations.AddIndex(
            model_name='salesheader',
            index=models.Index(fields=['entitas_bisnis', 'tanggal_transaksi'], name='idx_sh_entitas_tanggal'),
        ),
        migrations.AddIndex(
            model_name='salesheader',
            index=models.Index(fields=['status_pengiriman', 'tanggal_transaksi'], name='idx_sh_status_tanggal'),
        ),
    ]
