# Generated by Django 6.0.4 on 2026-04-16 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0002_sales_eb_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesItemFIFOAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_consumed', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Qty Consumed')),
                ('cogs_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='COGS Amount')),
                ('inventory_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_allocations', to='inventory.inventoryrecord')),
                ('sales_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifo_allocations', to='sales.salesitem')),
            ],
            options={
                'verbose_name': 'Sales FIFO Allocation',
                'verbose_name_plural': 'Sales FIFO Allocations',
                'indexes': [models.Index(fields=['sales_item'], name='idx_sfa_sales_item'), models.Index(fields=['inventory_record'], name='idx_sfa_inv_record')],
            },
        ),
    ]
