# Generated by Django 6.0.4 on 2026-04-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_add_salesitem_fifo_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='hpp_terpakai',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Untuk item bulk: mengurangi nilai persediaan bulk.', max_digits=19, null=True, verbose_name='HPP Terpakai (Bulk)'),
        ),
    ]
