# Generated by Django 6.0.4 on 2026-04-17 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('sales', '0004_salesitem_hpp_terpakai'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_item_payment', to='master_data.akun', verbose_name='Payment Account'),
        ),
        migrations.AlterField(
            model_name='salesentitasbisnis',
            name='payment_account',
            field=models.ForeignKey(blank=True, help_text='Kas Tunai, Kas di Bank, dll. (Legacy — per-item payment_account di SalesItem lebih diutamakan).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_eb_payment', to='master_data.akun', verbose_name='Payment Account'),
        ),
    ]
