# Generated by Django 6.0.4 on 2026-06-05 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesitem_payment_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesheader',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat oleh'),
        ),
        migrations.CreateModel(
            name='SalesEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Dibuat'), ('EDITED', 'Diedit'), ('VOIDED', 'Dibatalkan'), ('FIFO_PROCESSED', 'FIFO Diproses'), ('JOURNAL_CREATED', 'Jurnal Dibuat'), ('PAYMENT_PROCESSED', 'Pembayaran Diproses'), ('LOCKED', 'Dikunci')], max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_event_logs', to=settings.AUTH_USER_MODEL)),
                ('sales_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='sales.salesheader')),
            ],
            options={
                'verbose_name': 'Sales Event Log',
                'verbose_name_plural': 'Sales Event Logs',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['sales_header', 'timestamp'], name='idx_sel_header_ts')],
            },
        ),
    ]
