# Generated by Django 6.0.4 on 2026-06-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salesheader_createdby_eventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesheader',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Kredit')], default='cash', max_length=10, verbose_name='Tipe Pembayaran'),
        ),
    ]
