# Generated by Django 6.0.6 on 2026-06-29 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('sales', '0007_salesheader_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTaxLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('ppn_keluaran', 'PPN Keluaran'), ('pph_23', 'PPh 23'), ('pph_21', 'PPh 21'), ('pph_4_2', 'PPh 4(2)')], max_length=30, verbose_name='Tipe Pajak')),
                ('tax', models.DecimalField(blank=True, decimal_places=4, help_text='Nominal pajak. Hasil hitung otomatis atau override manual (lihat is_manual).', max_digits=19, null=True, verbose_name='Pajak (Nominal)')),
                ('is_manual', models.BooleanField(default=False, help_text='True jika nominal pajak diisi/diubah manual. False = dihitung ulang dari tarif.', verbose_name='Override Manual')),
                ('sales_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_lines', to='sales.salesitem', verbose_name='Sales Item')),
                ('tax_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_tax_lines_pajak', to='master_data.akun', verbose_name='Akun Pajak')),
                ('tax_payment_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_tax_lines_lawan', to='master_data.akun', verbose_name='Akun Lawan Pajak')),
            ],
            options={
                'verbose_name': 'Sales Tax Line',
                'verbose_name_plural': 'Sales Tax Lines',
                'ordering': ['id'],
            },
        ),
    ]
