# Generated by Django 6.0.6 on 2026-07-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_stockmovement_warehouse_and_more'),
        ('sales', '0008_salestaxline'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_items', to='inventory.warehouse', verbose_name='Gudang'),
        ),
    ]
