# Generated by Django 6.0.4 on 2026-04-13 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('entitas_bisnis', '0003_cabangentitasbisnis_idx_cab_entitas_aktif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('business_owner', 'Pemilik Bisnis'), ('business_employee', 'Karyawan Bisnis')], max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Role',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role', verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='UserEntitasBisnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entitas_bisnis', to='entitas_bisnis.entitasbisnis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entitas_bisnis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Akses User ke Entitas Bisnis',
                'verbose_name_plural': 'Akses User ke Entitas Bisnis',
                'indexes': [models.Index(fields=['user', 'entitas_bisnis'], name='idx_ueb_user_entitas')],
                'unique_together': {('user', 'entitas_bisnis')},
            },
        ),
    ]
