# Generated by Django 6.0.4 on 2026-04-15 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # These are the old incremental migrations that were squashed into
    # accounts/0001_initial.py + this file.  On production databases that
    # already have these migrations applied, Django will treat this migration
    # as already applied and skip it — preventing AddField conflicts.
    replaces = [
        ('accounts', '0002_role_user_role_userentitasbisnis'),
        ('accounts', '0003_alter_user_role'),
        ('accounts', '0004_nipermission_role_deskripsi_user_ni_permissions'),
    ]

    dependencies = [
        ('accounts', '0001_initial'),
        ('entitas_bisnis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentitasbisnis',
            name='entitas_bisnis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entitas_bisnis', to='entitas_bisnis.entitasbisnis'),
        ),
        migrations.AddField(
            model_name='userentitasbisnis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entitas_bisnis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userentitasbisnis',
            index=models.Index(fields=['user', 'entitas_bisnis'], name='idx_ueb_user_entitas'),
        ),
        migrations.AlterUniqueTogether(
            name='userentitasbisnis',
            unique_together={('user', 'entitas_bisnis')},
        ),
    ]
