# Generated by Django 6.0.4 on 2026-05-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='kode',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('business_owner', 'Pemilik Bisnis'), ('business_employee', 'Karyawan Bisnis'), ('kasir', 'Kasir')], max_length=50, unique=True),
        ),
    ]
