# Generated by Django 6.0.4 on 2026-04-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Kode Permission')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Permission')),
                ('module', models.CharField(blank=True, default='', max_length=100, verbose_name='Modul')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='deskripsi',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='ni_permissions',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.nipermission', verbose_name='Permissions'),
        ),
    ]
