services:
  db:
    image: postgres:16
    container_name: naveda_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: naveda_web
    restart: always
    ports:
      - "8080:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data:
