# Generated by Django 6.0.4 on 2026-05-07 08:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos_catalog', '0001_initial'),
        ('pos_config', '0001_initial'),
        ('sales', '0005_salesitem_payment_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('source', models.CharField(choices=[('POS', 'POS'), ('GOFOOD', 'GoFood'), ('GRABFOOD', 'GrabFood'), ('SHOPEEFOOD', 'ShopeeFood'), ('SHOPEE', 'Shopee'), ('OTHER', 'Lainnya')], default='POS', max_length=20)),
                ('external_order_id', models.CharField(blank=True, max_length=100)),
                ('external_order_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Terbuka'), ('IN_QUEUE', 'Dalam Antrian'), ('PREPARING', 'Diproses'), ('READY', 'Siap'), ('COMPLETED', 'Selesai'), ('CANCELLED', 'Dibatalkan'), ('REFUNDED', 'Direfund')], db_index=True, default='DRAFT', max_length=20)),
                ('order_type', models.CharField(choices=[('DINE_IN', 'Makan di Tempat'), ('TAKEAWAY', 'Bawa Pulang'), ('DELIVERY', 'Pesan Antar')], default='DINE_IN', max_length=20)),
                ('table_number', models.CharField(blank=True, max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('service_charge_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashier_orders', to=settings.AUTH_USER_MODEL)),
                ('sales_header', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_order', to='sales.salesheader')),
                ('shift_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pos_config.shiftlog')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='pos_config.storeposconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('modifier_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu'), ('PREPARING', 'Diproses'), ('READY', 'Siap'), ('CANCELLED', 'Dibatalkan')], default='PENDING', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos_orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='pos_catalog.posproduct')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name_snapshot', models.CharField(max_length=100)),
                ('group_name_snapshot', models.CharField(max_length=100)),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modifier_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos_catalog.modifieroption')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='pos_orders.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos_orders.order')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos_config.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('refund_type', models.CharField(choices=[('FULL', 'Full'), ('PARTIAL', 'Parsial')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu'), ('APPROVED', 'Disetujui'), ('COMPLETED', 'Selesai'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refunds', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_refunds', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='pos_orders.order')),
                ('refund_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos_config.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos_orders.orderitem')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos_orders.refund')),
            ],
        ),
    ]
