# Generated by Django 6.0.4 on 2026-05-12 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_catalog', '0002_remove_pos_product_models'),
        ('pos_orders', '0003_order_member'),
        ('purchase', '0003_add_nilai_residu_to_item_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='purchase.itemmasterpurchase'),
        ),
    ]
