# Generated by Django 6.0.4 on 2026-04-15 18:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitas_bisnis', '0001_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Item',
            },
        ),
        migrations.CreateModel(
            name='JurnalAutomasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Jurnal Automasi',
                'verbose_name_plural': 'Jurnal Automasi',
            },
        ),
        migrations.CreateModel(
            name='TransactionPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Prefiks Transaksi',
                'verbose_name_plural': 'Prefiks Transaksi',
            },
        ),
        migrations.CreateModel(
            name='JurnalHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('nomor_transaksi', models.CharField(max_length=100, unique=True)),
                ('uraian_transaksi', models.CharField(max_length=512)),
                ('is_penyesuaian', models.BooleanField(default=False, help_text='True jika jurnal berasal dari penyesuaian manual, False jika dari modul otomatis.', verbose_name='Penyesuaian Manual')),
                ('entitas_bisnis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurnal_headers', to='entitas_bisnis.entitasbisnis')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jurnal_headers', to='jurnal.item')),
                ('no_bukti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurnal_headers', to='master_data.bukti')),
                ('tipe_transaksi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jurnal_headers', to='master_data.tipetransaksi')),
                ('transaction_prefix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jurnal_headers', to='jurnal.transactionprefix')),
            ],
            options={
                'verbose_name': 'Jurnal Header',
                'verbose_name_plural': 'Jurnal Header',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='JurnalAutomasiAkun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automasi_mappings', to='master_data.akun')),
                ('automasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='akun_mappings', to='jurnal.jurnalautomasi')),
            ],
            options={
                'verbose_name': 'Jurnal Automasi Akun',
                'verbose_name_plural': 'Jurnal Automasi Akun',
                'unique_together': {('automasi', 'akun')},
            },
        ),
        migrations.CreateModel(
            name='JurnalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('kredit', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurnal_details', to='master_data.akun')),
                ('jurnal_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='jurnal.jurnalheader')),
            ],
            options={
                'verbose_name': 'Jurnal Detail',
                'verbose_name_plural': 'Jurnal Detail',
                'indexes': [models.Index(fields=['akun', 'jurnal_header'], name='idx_jd_akun_header'), models.Index(fields=['jurnal_header', 'akun'], name='idx_jd_header_akun')],
            },
        ),
        migrations.AddIndex(
            model_name='jurnalheader',
            index=models.Index(fields=['tanggal', 'tipe_transaksi'], name='idx_jh_tanggal_tipe'),
        ),
        migrations.AddIndex(
            model_name='jurnalheader',
            index=models.Index(fields=['entitas_bisnis', 'tanggal'], name='idx_jh_entitas_tanggal'),
        ),
        migrations.AddIndex(
            model_name='jurnalheader',
            index=models.Index(fields=['item'], name='idx_jh_item'),
        ),
    ]
