# Generated by Django 6.0.4 on 2026-04-10 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitas_bisnis', '0001_initial'),
        ('master_data', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JurnalHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('uraian_transaksi', models.CharField(max_length=512)),
                ('entitas_bisnis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurnal_headers', to='entitas_bisnis.entitasbisnis')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurnal_headers', to='sales.itemmaster')),
                ('no_bukti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurnal_headers', to='master_data.bukti')),
                ('tipe_transaksi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurnal_headers', to='master_data.tipetransaksi')),
            ],
            options={
                'verbose_name': 'Jurnal Header',
                'verbose_name_plural': 'Jurnal Header',
            },
        ),
        migrations.CreateModel(
            name='JurnalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('kredit', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurnal_details', to='master_data.akun')),
                ('jurnal_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='jurnal.jurnalheader')),
            ],
            options={
                'verbose_name': 'Jurnal Detail',
                'verbose_name_plural': 'Jurnal Detail',
            },
        ),
    ]
