# Generated by Django 6.0.4 on 2026-04-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0003_cabangentitasbisnis_idx_cab_entitas_aktif_and_more'),
        ('jurnal', '0001_initial'),
        ('master_data', '0002_alter_akun_kategori_akun_alter_akun_kategori_id_and_more'),
        ('sales', '0002_alter_salesheader_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jurnalheader',
            options={'ordering': ['-tanggal'], 'verbose_name': 'Jurnal Header', 'verbose_name_plural': 'Jurnal Header'},
        ),
        migrations.AlterField(
            model_name='jurnalheader',
            name='tanggal',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='jurnaldetail',
            index=models.Index(fields=['akun', 'jurnal_header'], name='idx_jd_akun_header'),
        ),
        migrations.AddIndex(
            model_name='jurnaldetail',
            index=models.Index(fields=['jurnal_header', 'akun'], name='idx_jd_header_akun'),
        ),
        migrations.AddIndex(
            model_name='jurnalheader',
            index=models.Index(fields=['tanggal', 'tipe_transaksi'], name='idx_jh_tanggal_tipe'),
        ),
        migrations.AddIndex(
            model_name='jurnalheader',
            index=models.Index(fields=['entitas_bisnis', 'tanggal'], name='idx_jh_entitas_tanggal'),
        ),
        migrations.AddIndex(
            model_name='jurnalheader',
            index=models.Index(fields=['item'], name='idx_jh_item'),
        ),
    ]
