# Generated by Django 6.0.4 on 2026-04-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnalheader',
            name='is_saldo_awal',
            field=models.BooleanField(default=False, help_text='True jika jurnal merupakan entry saldo awal.', verbose_name='Saldo Awal'),
        ),
    ]
