# Generated by Django 6.0.4 on 2026-04-18 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0002_jurnalheader_is_saldo_awal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JurnalTerhapus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_transaksi', models.CharField(db_index=True, max_length=100, verbose_name='Nomor Transaksi')),
                ('uraian_transaksi', models.CharField(max_length=512, verbose_name='Uraian')),
                ('entitas_bisnis_nama', models.CharField(blank=True, max_length=255, verbose_name='Entitas Bisnis')),
                ('tanggal', models.DateField(blank=True, null=True, verbose_name='Tanggal Transaksi')),
                ('module', models.CharField(choices=[('ekuitas', 'Modal Disetor'), ('purchase', 'Purchase'), ('sales', 'Sales'), ('inventory', 'Inventory'), ('aset_tetap', 'Aset Tetap'), ('aset_lainnya', 'Aset Lainnya'), ('manual', 'Jurnal Manual'), ('saldo_awal', 'Saldo Awal'), ('lainnya', 'Lainnya')], default='lainnya', max_length=50, verbose_name='Modul')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Dihapus Pada')),
                ('detail_snapshot', models.JSONField(default=list, help_text='Snapshot baris debit/kredit sebelum jurnal dihapus.', verbose_name='Detail Jurnal (Snapshot)')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurnal_terhapus', to=settings.AUTH_USER_MODEL, verbose_name='Dihapus Oleh')),
            ],
            options={
                'verbose_name': 'Jurnal Terhapus',
                'verbose_name_plural': 'Jurnal Terhapus',
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['module', 'deleted_at'], name='idx_jt_module_deleted')],
            },
        ),
    ]
