# Generated by Django 6.0.4 on 2026-04-10 18:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0002_alter_jurnalheader_options_and_more'),
        ('master_data', '0003_akun_nama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Item',
            },
        ),
        migrations.CreateModel(
            name='JurnalAutomasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Jurnal Automasi',
                'verbose_name_plural': 'Jurnal Automasi',
            },
        ),
        migrations.CreateModel(
            name='TransactionPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Prefiks Transaksi',
                'verbose_name_plural': 'Prefiks Transaksi',
            },
        ),
        migrations.AddField(
            model_name='jurnalheader',
            name='nomor_transaksi',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jurnalheader',
            name='tanggal',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jurnalheader',
            name='tipe_transaksi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jurnal_headers', to='master_data.tipetransaksi'),
        ),
        migrations.AlterField(
            model_name='jurnalheader',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jurnal_headers', to='jurnal.item'),
        ),
        migrations.AddField(
            model_name='jurnalheader',
            name='transaction_prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jurnal_headers', to='jurnal.transactionprefix'),
        ),
        migrations.CreateModel(
            name='JurnalAutomasiAkun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automasi_mappings', to='master_data.akun')),
                ('automasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='akun_mappings', to='jurnal.jurnalautomasi')),
            ],
            options={
                'verbose_name': 'Jurnal Automasi Akun',
                'verbose_name_plural': 'Jurnal Automasi Akun',
                'unique_together': {('automasi', 'akun')},
            },
        ),
    ]
