# Generated by Django 6.0.4 on 2026-04-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0003_item_jurnalautomasi_transactionprefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnalheader',
            name='is_penyesuaian',
            field=models.BooleanField(default=False, help_text='True jika jurnal berasal dari penyesuaian manual, False jika dari modul otomatis.', verbose_name='Penyesuaian Manual'),
        ),
    ]
