# Generated by Django 6.0.4 on 2026-04-10 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitas_bisnis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiutangHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dll', models.CharField(blank=True, max_length=50)),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piutang_headers', to='entitas_bisnis.entitasbisnis')),
            ],
            options={
                'verbose_name': 'Piutang Header',
                'verbose_name_plural': 'Piutang Header',
            },
        ),
        migrations.CreateModel(
            name='PiutangDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dll', models.CharField(blank=True, max_length=50)),
                ('piutang_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='piutang.piutangheader')),
            ],
            options={
                'verbose_name': 'Piutang Detail',
                'verbose_name_plural': 'Piutang Detail',
            },
        ),
    ]
