# Generated by Django 6.0.4 on 2026-06-08 05:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitas_bisnis', '0002_is_company_profile'),
        ('jurnal', '0003_add_jurnal_terhapus_and_persentase'),
        ('master_data', '0001_initial'),
        ('purchase', '0005_subtransactiontype_payment_term_days'),
        ('sales', '0006_salesheader_createdby_eventlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PiutangHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_piutang', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Nomor Piutang')),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Tanggal')),
                ('jatuh_tempo', models.DateField(blank=True, db_index=True, null=True, verbose_name='Jatuh Tempo')),
                ('debitur', models.CharField(blank=True, default='', max_length=255, verbose_name='Debitur')),
                ('deskripsi', models.CharField(blank=True, default='', max_length=512, verbose_name='Deskripsi')),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('from_sales', 'Dari Sales'), ('from_pendapatan', 'Dari Pendapatan')], default='manual', max_length=20, verbose_name='Sumber')),
                ('jumlah_pokok', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Jumlah Pokok')),
                ('jumlah_terbayar', models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Jumlah Terbayar')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Terbuka'), ('partial', 'Sebagian Diterima'), ('paid', 'Lunas'), ('overdue', 'Jatuh Tempo'), ('written_off', 'Dihapusbukukan'), ('cancelled', 'Dibatalkan')], default='draft', max_length=20, verbose_name='Status')),
                ('jenis_jangka_waktu', models.CharField(choices=[('short_term', 'Jangka Pendek'), ('long_term', 'Jangka Panjang')], default='short_term', max_length=20, verbose_name='Jenis Jangka Waktu')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Perlu Persetujuan')),
                ('approval_status', models.CharField(blank=True, choices=[('', '-'), ('pending', 'Menunggu'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='', max_length=20, verbose_name='Status Persetujuan')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Disetujui Pada')),
                ('jenis_bunga', models.CharField(choices=[('tanpa_bunga', 'Tanpa Bunga'), ('flat', 'Flat'), ('anuitas', 'Anuitas (Efektif)')], default='tanpa_bunga', max_length=20, verbose_name='Jenis Bunga')),
                ('bunga_persen', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Suku Bunga (% per tahun)')),
                ('jumlah_angsuran', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jumlah Angsuran')),
                ('periode_angsuran', models.CharField(choices=[('bulanan', 'Bulanan'), ('triwulanan', 'Triwulanan (3 Bulan)'), ('semesteran', 'Semesteran (6 Bulan)'), ('tahunan', 'Tahunan')], default='bulanan', max_length=20, verbose_name='Periode Angsuran')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Terkunci')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_approved', to=settings.AUTH_USER_MODEL, verbose_name='Disetujui Oleh')),
                ('coa_piutang_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piutang_headers', to='master_data.akun', verbose_name='Akun Piutang')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('entitas_bisnis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_headers', to='entitas_bisnis.entitasbisnis', verbose_name='Entitas Bisnis')),
                ('source_sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_headers', to='sales.salesheader', verbose_name='Sales Header')),
            ],
            options={
                'verbose_name': 'Piutang Header',
                'verbose_name_plural': 'Piutang Header',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PiutangDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(blank=True, default='', max_length=255, verbose_name='Deskripsi')),
                ('jumlah', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Jumlah')),
                ('revenue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='piutang_details', to='master_data.akun', verbose_name='Akun Pendapatan')),
                ('sub_transaction_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_details', to='purchase.subtransactiontype', verbose_name='Sub-Tipe Transaksi')),
                ('piutang_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='piutang.piutangheader', verbose_name='Piutang Header')),
            ],
            options={
                'verbose_name': 'Piutang Detail',
                'verbose_name_plural': 'Piutang Detail',
            },
        ),
        migrations.CreateModel(
            name='PiutangAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_piutang', models.CharField(blank=True, default='', max_length=100, verbose_name='Nomor Piutang')),
                ('action', models.CharField(choices=[('CREATED', 'Dibuat'), ('EDITED', 'Diedit'), ('SUBMIT_APPROVAL', 'Diajukan Persetujuan'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak'), ('PAYMENT', 'Penerimaan'), ('REVERSE_PAYMENT', 'Batalkan Penerimaan'), ('WRITE_OFF', 'Dihapusbukukan'), ('REKLASIFIKASI', 'Reklasifikasi'), ('CANCELLED', 'Dibatalkan')], max_length=30, verbose_name='Aksi')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Waktu')),
                ('before_json', models.JSONField(blank=True, default=dict, verbose_name='Sebelum')),
                ('after_json', models.JSONField(blank=True, default=dict, verbose_name='Sesudah')),
                ('notes', models.CharField(blank=True, default='', max_length=512, verbose_name='Catatan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('piutang_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='piutang.piutangheader', verbose_name='Piutang Header')),
            ],
            options={
                'verbose_name': 'Audit Log Piutang',
                'verbose_name_plural': 'Audit Log Piutang',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PiutangAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='piutang/attachments/%Y/%m/', verbose_name='File')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nama File')),
                ('jenis_dokumen', models.CharField(choices=[('invoice', 'Invoice'), ('kontrak', 'Kontrak'), ('spk', 'SPK'), ('perjanjian', 'Perjanjian'), ('berita_acara', 'Berita Acara'), ('kuitansi', 'Kuitansi'), ('lainnya', 'Lainnya')], default='lainnya', max_length=30, verbose_name='Jenis Dokumen')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Diupload Pada')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Diupload Oleh')),
                ('piutang_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='piutang.piutangheader', verbose_name='Piutang Header')),
            ],
            options={
                'verbose_name': 'Lampiran Piutang',
                'verbose_name_plural': 'Lampiran Piutang',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PiutangPenerimaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_terima', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Tanggal Terima')),
                ('jumlah_diterima', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Jumlah Diterima')),
                ('angsuran_no', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='No. Angsuran')),
                ('metode_penerimaan', models.CharField(choices=[('transfer', 'Transfer'), ('tunai', 'Tunai'), ('giro', 'Giro'), ('cek', 'Cek')], default='transfer', max_length=20, verbose_name='Metode Penerimaan')),
                ('nomor_referensi', models.CharField(blank=True, default='', max_length=100, verbose_name='No. Referensi')),
                ('catatan', models.CharField(blank=True, default='', max_length=512, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_penerimaan_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('jurnal_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_penerimaan', to='jurnal.jurnalheader', verbose_name='Jurnal')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piutang_penerimaan', to='master_data.akun', verbose_name='Akun Penerimaan')),
                ('piutang_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penerimaan', to='piutang.piutangheader', verbose_name='Piutang Header')),
            ],
            options={
                'verbose_name': 'Penerimaan Piutang',
                'verbose_name_plural': 'Penerimaan Piutang',
                'ordering': ['-tanggal_terima', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PiutangReklasifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('jumlah', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Jumlah')),
                ('keterangan', models.CharField(blank=True, default='', max_length=255, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_rkl_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('dari_akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piutang_rkl_dari', to='master_data.akun', verbose_name='Dari Akun')),
                ('jurnal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='piutang_reklasifikasi', to='jurnal.jurnalheader', verbose_name='Jurnal')),
                ('ke_akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piutang_rkl_ke', to='master_data.akun', verbose_name='Ke Akun')),
                ('piutang_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reklasifikasi_entries', to='piutang.piutangheader', verbose_name='Piutang Header')),
            ],
            options={
                'verbose_name': 'Reklasifikasi Piutang',
                'verbose_name_plural': 'Reklasifikasi Piutang',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PiutangWriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('jumlah_dihapus', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Jumlah Dihapus')),
                ('metode', models.CharField(choices=[('langsung', 'Langsung'), ('cadangan', 'Cadangan Kerugian')], max_length=20, verbose_name='Metode')),
                ('alasan', models.TextField(blank=True, default='', verbose_name='Alasan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowance_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='piutang_write_off_allowance', to='master_data.akun', verbose_name='Akun Cadangan Kerugian Piutang')),
                ('bad_debt_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piutang_write_off_bad_debt', to='master_data.akun', verbose_name='Akun Beban Piutang Tak Tertagih')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_write_off_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('jurnal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_write_offs', to='jurnal.jurnalheader', verbose_name='Jurnal')),
                ('piutang_header', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='write_off', to='piutang.piutangheader', verbose_name='Piutang Header')),
            ],
            options={
                'verbose_name': 'Write-Off Piutang',
                'verbose_name_plural': 'Write-Off Piutang',
            },
        ),
        migrations.AddIndex(
            model_name='piutangheader',
            index=models.Index(fields=['tanggal', 'status'], name='idx_ph_tanggal_status'),
        ),
        migrations.AddIndex(
            model_name='piutangheader',
            index=models.Index(fields=['source_type', 'status'], name='idx_ph_source_status'),
        ),
        migrations.AddIndex(
            model_name='piutangheader',
            index=models.Index(fields=['jatuh_tempo'], name='idx_ph_jatuh_tempo'),
        ),
        migrations.AddIndex(
            model_name='piutangauditlog',
            index=models.Index(fields=['nomor_piutang', 'timestamp'], name='idx_pal_nomor_ts'),
        ),
        migrations.AddIndex(
            model_name='piutangpenerimaan',
            index=models.Index(fields=['piutang_header', 'tanggal_terima'], name='idx_pp_header_tanggal'),
        ),
    ]
