# Generated by Django 6.0.4 on 2026-06-08 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendapatan', '0001_initial'),
        ('piutang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piutangheader',
            name='source_pendapatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_headers', to='pendapatan.pendapatanheader', verbose_name='Pendapatan Header'),
        ),
    ]
