# Generated by Django 6.0.4 on 2026-06-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piutang', '0002_add_source_pendapatan_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piutangheader',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='piutangheader',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='piutangheader',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='piutangheader',
            name='bunga_persen',
        ),
        migrations.RemoveField(
            model_name='piutangheader',
            name='jenis_bunga',
        ),
        migrations.RemoveField(
            model_name='piutangheader',
            name='jumlah_angsuran',
        ),
        migrations.RemoveField(
            model_name='piutangheader',
            name='periode_angsuran',
        ),
        migrations.RemoveField(
            model_name='piutangheader',
            name='requires_approval',
        ),
        migrations.AlterField(
            model_name='piutangauditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Dibuat'), ('EDITED', 'Diedit'), ('PAYMENT', 'Penerimaan'), ('REVERSE_PAYMENT', 'Batalkan Penerimaan'), ('WRITE_OFF', 'Dihapusbukukan'), ('REKLASIFIKASI', 'Reklasifikasi'), ('CANCELLED', 'Dibatalkan')], max_length=30, verbose_name='Aksi'),
        ),
    ]
