# Generated by Django 6.0.4 on 2026-06-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piutang', '0003_remove_piutangheader_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piutangheader',
            name='is_specifically_impaired',
            field=models.BooleanField(default=False, verbose_name='Sudah Disisihkan Khusus'),
        ),
        migrations.AddField(
            model_name='piutangheader',
            name='jenis_bunga',
            field=models.CharField(choices=[('tanpa_bunga', 'Tanpa Bunga'), ('flat', 'Flat'), ('anuitas', 'Anuitas (Efektif)')], default='tanpa_bunga', max_length=20, verbose_name='Jenis Bunga'),
        ),
        migrations.AddField(
            model_name='piutangheader',
            name='periode_angsuran',
            field=models.CharField(choices=[('bulanan', 'Bulanan'), ('triwulanan', 'Triwulanan (3 Bulan)'), ('semesteran', 'Semesteran (6 Bulan)'), ('tahunan', 'Tahunan')], default='bulanan', max_length=20, verbose_name='Periode Angsuran'),
        ),
        migrations.AddField(
            model_name='piutangheader',
            name='suku_bunga',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Suku Bunga (% per tahun)'),
        ),
    ]
