# Generated by Django 6.0.4 on 2026-06-09 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0003_add_jurnal_terhapus_and_persentase'),
        ('master_data', '0001_initial'),
        ('piutang', '0004_piutang_angsuran_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenyisihanRateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_key', models.CharField(choices=[('current', 'Belum Jatuh Tempo'), ('1_30', 'Lewat 1–30 Hari'), ('31_60', 'Lewat 31–60 Hari'), ('61_90', 'Lewat 61–90 Hari'), ('91_180', 'Lewat 91–180 Hari'), ('181_365', 'Lewat 181–365 Hari'), ('over_365', 'Lewat > 365 Hari')], max_length=20, unique=True, verbose_name='Bucket')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rate Penyisihan (%)')),
                ('urutan', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
            ],
            options={
                'verbose_name': 'Rate Penyisihan Piutang',
                'verbose_name_plural': 'Rate Penyisihan Piutang',
                'ordering': ['urutan'],
            },
        ),
        migrations.AlterField(
            model_name='piutangauditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Dibuat'), ('EDITED', 'Diedit'), ('PAYMENT', 'Penerimaan'), ('REVERSE_PAYMENT', 'Batalkan Penerimaan'), ('WRITE_OFF', 'Dihapusbukukan'), ('REKLASIFIKASI', 'Reklasifikasi'), ('CANCELLED', 'Dibatalkan'), ('PENYISIHAN', 'Penyisihan Piutang')], max_length=30, verbose_name='Aksi'),
        ),
        migrations.CreateModel(
            name='PiutangPenyisihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('jenis', models.CharField(choices=[('manual', 'Manual (Per-Piutang)'), ('batch', 'Batch Akhir Periode')], max_length=10, verbose_name='Jenis')),
                ('jumlah', models.DecimalField(decimal_places=4, help_text='Positif = beban penyisihan, negatif = pemulihan', max_digits=19, verbose_name='Jumlah')),
                ('catatan', models.CharField(blank=True, default='', max_length=512, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowance_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piutang_penyisihan_allowance', to='master_data.akun', verbose_name='Akun Cadangan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_penyisihan_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piutang_penyisihan_expense', to='master_data.akun', verbose_name='Akun Beban')),
                ('jurnal_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_penyisihan', to='jurnal.jurnalheader', verbose_name='Jurnal')),
                ('piutang_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penyisihan_entries', to='piutang.piutangheader', verbose_name='Piutang Header')),
            ],
            options={
                'verbose_name': 'Penyisihan Piutang',
                'verbose_name_plural': 'Penyisihan Piutang',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
    ]
