# Generated by Django 6.0.6 on 2026-06-14 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('piutang', '0010_piutangheader_posting_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='piutangheader',
            name='deferred_income_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='piutang_deferred_income', to='master_data.akun', verbose_name='Akun Pendapatan Bunga Ditangguhkan'),
        ),
    ]
