# Generated by Django 6.0.6 on 2026-06-14 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('piutang', '0011_deferred_income_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='piutangheader',
            name='interest_income_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='piutang_interest_income', to='master_data.akun', verbose_name='Akun Pendapatan Bunga Efektif'),
        ),
        migrations.AlterField(
            model_name='piutangheader',
            name='pv_discount_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Market Rate / Bunga Pasar untuk PV (%/tahun)'),
        ),
    ]
