# Generated by Django 6.0.6 on 2026-06-17 10:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0003_add_jurnal_terhapus_and_persentase'),
        ('master_data', '0001_initial'),
        ('piutang', '0015_piutangpenyisihan_entitas_bisnis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='piutangheader',
            name='agunan_jenis',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Jenis Agunan / Kolateral'),
        ),
        migrations.AddField(
            model_name='piutangheader',
            name='agunan_nilai',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='Nilai Agunan (Estimasi)'),
        ),
        migrations.AddField(
            model_name='piutangheader',
            name='biaya_transaksi',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Biaya transaksi yang dikapitalisasi ke nilai tercatat awal (menaikkan EIR efektif).', max_digits=19, verbose_name='Biaya Transaksi Dikapitalisasi'),
        ),
        migrations.AddField(
            model_name='piutangheader',
            name='biaya_transaksi_account',
            field=models.ForeignKey(blank=True, help_text='Akun kredit offset biaya transaksi yang dikapitalisasi (biasanya Kas/Bank).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='piutang_biaya_transaksi', to='master_data.akun', verbose_name='Akun Offset Biaya Transaksi'),
        ),
        migrations.AddField(
            model_name='piutangheader',
            name='business_model',
            field=models.CharField(blank=True, choices=[('hold_to_collect', 'Hold to Collect'), ('hold_to_collect_and_sell', 'Hold to Collect & Sell'), ('other', 'Other / Trading')], default='', help_text='Hasil Business Model Test (PSAK 71 / IFRS 9).', max_length=30, verbose_name='Business Model Test'),
        ),
        migrations.AddField(
            model_name='piutangheader',
            name='kategori_pengukuran',
            field=models.CharField(choices=[('amortised_cost', 'Biaya Perolehan Diamortisasi (Amortised Cost)'), ('fvoci', 'Nilai Wajar Melalui OCI (FVOCI)'), ('fvpl', 'Nilai Wajar Melalui Laba Rugi (FVPL)')], default='amortised_cost', max_length=20, verbose_name='Kategori Pengukuran'),
        ),
        migrations.AddField(
            model_name='piutangheader',
            name='sppi_test_passed',
            field=models.BooleanField(blank=True, help_text='Solely Payments of Principal and Interest test.', null=True, verbose_name='SPPI Test Lulus'),
        ),
        migrations.AddField(
            model_name='piutangheader',
            name='stage_ecl',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Stage 1 — Performing (ECL 12 Bulan)'), (2, 'Stage 2 — SICR (ECL Seumur Hidup)'), (3, 'Stage 3 — Credit-Impaired (ECL Seumur Hidup, Bunga atas Neto)')], help_text='PSAK General Approach: Stage 1/2/3. Kosong = Simplified Approach.', null=True, verbose_name='Stage ECL'),
        ),
        migrations.AddField(
            model_name='piutangheader',
            name='stage_ecl_tanggal',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Perubahan Stage ECL'),
        ),
        migrations.AddField(
            model_name='piutangheader',
            name='standar_akuntansi',
            field=models.CharField(blank=True, choices=[('psak', 'PSAK (PSAK 71 / Full IFRS)'), ('sak_ep', 'SAK EP (Entitas Privat)'), ('sak_emkm', 'SAK EMKM (Entitas Mikro, Kecil, Menengah)')], default='', help_text='Kosongkan untuk mengikuti standar entitas bisnis. Isi untuk override.', max_length=10, verbose_name='Standar Akuntansi (Override)'),
        ),
        migrations.AlterField(
            model_name='piutangauditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Dibuat'), ('EDITED', 'Diedit'), ('POSTED', 'Diposting'), ('SUBMITTED', 'Disubmit Approval'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak'), ('PAYMENT', 'Penerimaan'), ('REVERSE_PAYMENT', 'Batalkan Penerimaan'), ('WRITE_OFF', 'Dihapusbukukan'), ('REKLASIFIKASI', 'Reklasifikasi'), ('CANCELLED', 'Dibatalkan'), ('PENYISIHAN', 'Penyisihan Piutang'), ('ECL_STAGING', 'Perubahan Stage ECL'), ('MODIFIKASI', 'Modifikasi Syarat'), ('RECOVERY', 'Pemulihan Write-Off'), ('FACTORING', 'Transfer/Factoring')], max_length=30, verbose_name='Aksi'),
        ),
        migrations.CreateModel(
            name='PiutangECLStagingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_dari', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Stage 1 — Performing (ECL 12 Bulan)'), (2, 'Stage 2 — SICR (ECL Seumur Hidup)'), (3, 'Stage 3 — Credit-Impaired (ECL Seumur Hidup, Bunga atas Neto)')], null=True, verbose_name='Stage Sebelumnya')),
                ('stage_ke', models.PositiveSmallIntegerField(choices=[(1, 'Stage 1 — Performing (ECL 12 Bulan)'), (2, 'Stage 2 — SICR (ECL Seumur Hidup)'), (3, 'Stage 3 — Credit-Impaired (ECL Seumur Hidup, Bunga atas Neto)')], verbose_name='Stage Baru')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('days_past_due', models.PositiveIntegerField(default=0, verbose_name='Hari Keterlambatan')),
                ('alasan', models.TextField(blank=True, default='', verbose_name='Alasan')),
                ('is_auto', models.BooleanField(default=True, verbose_name='Otomatis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecl_staging_logs', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('piutang_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecl_staging_logs', to='piutang.piutangheader', verbose_name='Piutang Header')),
            ],
            options={
                'verbose_name': 'Log Staging ECL',
                'verbose_name_plural': 'Log Staging ECL',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PiutangFactoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal Transfer')),
                ('nilai_transfer', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Nilai Transfer ke Pihak Lain')),
                ('hasil_analisis', models.CharField(choices=[('derecognized', 'Diderecognize Penuh (Semua Risiko & Manfaat Ditransfer)'), ('continuing', 'Continuing Involvement (Sebagian Risiko Ditahan)'), ('not_derecognized', 'Tidak Diderecognize (Risiko Ditahan Sepenuhnya)')], max_length=20, verbose_name='Hasil Analisis Risiko & Manfaat')),
                ('continuing_involvement_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='Jumlah Continuing Involvement')),
                ('gain_loss_derecognition', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='Gain / (Loss) Derecognition')),
                ('pihak_penerima', models.CharField(blank=True, default='', max_length=255, verbose_name='Pihak Penerima')),
                ('analisis_detail', models.TextField(blank=True, default='', verbose_name='Detail Analisis Risiko & Manfaat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_factoring_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('jurnal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_factoring', to='jurnal.jurnalheader', verbose_name='Jurnal')),
                ('piutang_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factoring_entries', to='piutang.piutangheader', verbose_name='Piutang Header')),
            ],
            options={
                'verbose_name': 'Factoring / Transfer Piutang',
                'verbose_name_plural': 'Factoring / Transfer Piutang',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PiutangModifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal Modifikasi')),
                ('carrying_amount_lama', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Carrying Amount Sebelum Modifikasi')),
                ('pv_syarat_baru', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='PV Arus Kas Syarat Baru (diskonto EIR lama)')),
                ('modification_gain_loss', models.DecimalField(decimal_places=4, help_text='PV baru − Carrying amount lama. Positif = gain, negatif = loss.', max_digits=19, verbose_name='Gain / (Loss) Modifikasi')),
                ('eir_baru', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='EIR Baru (% per tahun)')),
                ('deskripsi_perubahan', models.TextField(blank=True, default='', verbose_name='Deskripsi Perubahan Syarat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_modifikasi_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('gain_loss_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piutang_modifikasi_gl', to='master_data.akun', verbose_name='Akun Gain/Loss Modifikasi')),
                ('jurnal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_modifikasi', to='jurnal.jurnalheader', verbose_name='Jurnal')),
                ('piutang_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifikasi_entries', to='piutang.piutangheader', verbose_name='Piutang Header')),
            ],
            options={
                'verbose_name': 'Modifikasi Piutang',
                'verbose_name_plural': 'Modifikasi Piutang',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PiutangPemulihanWriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal Pemulihan')),
                ('jumlah_dipulihkan', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Jumlah Dipulihkan')),
                ('catatan', models.TextField(blank=True, default='', verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_pemulihan_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('jurnal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_pemulihan', to='jurnal.jurnalheader', verbose_name='Jurnal')),
                ('kas_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piutang_pemulihan_kas', to='master_data.akun', verbose_name='Akun Kas/Bank Penerimaan')),
                ('piutang_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemulihan_entries', to='piutang.piutangheader', verbose_name='Piutang Header')),
                ('recovery_income_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piutang_pemulihan_income', to='master_data.akun', verbose_name='Akun Pendapatan Pemulihan')),
            ],
            options={
                'verbose_name': 'Pemulihan Write-Off Piutang',
                'verbose_name_plural': 'Pemulihan Write-Off Piutang',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
    ]
