# Generated by Django 6.0.4 on 2026-05-07 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitas_bisnis', '0002_is_company_profile'),
        ('pos_config', '0002_merchant_accounting_fields'),
        ('pos_orders', '0002_alter_order_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('tier', models.CharField(choices=[('REGULAR', 'Regular'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='REGULAR', max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_orders', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('entitas_bisnis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profiles', to='entitas_bisnis.entitasbisnis')),
                ('merchant_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pos_config.merchantposconfig')),
            ],
            options={
                'unique_together': {('merchant_config', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='MemberPointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_logs', to='pos_crm.member')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='MemberTierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('REGULAR', 'Regular'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], max_length=20)),
                ('min_total_spent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('points_per_thousand', models.IntegerField(default=1)),
                ('point_value', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('merchant_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_configs', to='pos_config.merchantposconfig')),
            ],
            options={
                'unique_together': {('merchant_config', 'tier')},
            },
        ),
    ]
