# Generated by Django 6.0.4 on 2026-04-16 14:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitas_bisnis', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsetTetapRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aset_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Nomor Aset')),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=15, verbose_name='Quantity')),
                ('harga_perolehan', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Harga Perolehan')),
                ('total_value', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=19, verbose_name='Nilai Perolehan')),
                ('akumulasi_penyusutan', models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Akumulasi Penyusutan')),
                ('tanggal_perolehan', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Tanggal Perolehan')),
                ('masa_manfaat', models.PositiveIntegerField(blank=True, help_text='Override masa manfaat dari item master. Kosongkan untuk menggunakan nilai item master.', null=True, verbose_name='Masa Manfaat (Tahun)')),
                ('metode_penyusutan', models.CharField(blank=True, choices=[('straight_line', 'Garis Lurus (Straight Line)'), ('double_declining', 'Saldo Menurun (Double Declining Balance)'), ('sum_of_years', 'Jumlah Angka Tahun (Sum of The Year Digit)'), ('service_hours', 'Satuan Jam Kerja (Service Hours)'), ('units_of_production', 'Satuan Hasil Produksi (Productive Output)')], default='', help_text='Override metode penyusutan dari item master.', max_length=30, verbose_name='Metode Penyusutan')),
                ('lokasi', models.CharField(blank=True, max_length=255, verbose_name='Lokasi Aset')),
                ('kondisi', models.CharField(choices=[('baik', 'Baik'), ('rusak_ringan', 'Rusak Ringan'), ('rusak_berat', 'Rusak Berat'), ('dalam_perbaikan', 'Dalam Perbaikan')], default='baik', max_length=20, verbose_name='Kondisi Aset')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aset_tetap_records', to='entitas_bisnis.entitasbisnis', verbose_name='Entitas Bisnis')),
                ('item', models.ForeignKey(limit_choices_to={'tipe_item': 'ATP'}, on_delete=django.db.models.deletion.PROTECT, related_name='aset_tetap_records', to='purchase.itemmasterpurchase', verbose_name='Item Master')),
                ('purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aset_tetap_records', to='purchase.purchaseitem', verbose_name='Purchase Item')),
            ],
            options={
                'verbose_name': 'Aset Tetap Record',
                'verbose_name_plural': 'Aset Tetap Records',
                'ordering': ['-tanggal_perolehan', '-created_at'],
                'indexes': [models.Index(fields=['item', 'tanggal_perolehan'], name='idx_atr_item_tanggal'), models.Index(fields=['entitas_bisnis', 'tanggal_perolehan'], name='idx_atr_eb_tanggal'), models.Index(fields=['aset_number'], name='idx_atr_number')],
            },
        ),
    ]
