# Generated by Django 6.0.4 on 2026-04-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset_tetap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asettetaprecord',
            name='estimasi_jam_kerja',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total estimasi jam kerja selama masa manfaat (untuk metode Service Hours).', max_digits=15, null=True, verbose_name='Estimasi Total Jam Kerja'),
        ),
        migrations.AddField(
            model_name='asettetaprecord',
            name='estimasi_unit_produksi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total estimasi unit produksi selama masa manfaat (untuk metode Units of Production).', max_digits=15, null=True, verbose_name='Estimasi Total Unit Produksi'),
        ),
        migrations.AddField(
            model_name='asettetaprecord',
            name='nilai_residu',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Nilai sisa aset di akhir masa manfaat.', max_digits=19, verbose_name='Nilai Residu'),
        ),
    ]
