# Generated by Django 6.0.6 on 2026-07-17 10:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset_tetap', '0002_asettetaprecord_estimasi_jam_kerja_and_more'),
        ('jurnal', '0003_add_jurnal_terhapus_and_persentase'),
        ('master_data', '0002_akun_is_kas_setara'),
    ]

    operations = [
        migrations.AddField(
            model_name='asettetaprecord',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('dilepas', 'Dilepas')], db_index=True, default='aktif', max_length=10, verbose_name='Status Aset'),
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Nomor Pelepasan')),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Tanggal Pelepasan')),
                ('jenis', models.CharField(choices=[('jual', 'Jual'), ('hibah', 'Hibah'), ('rusak', 'Rusak'), ('musnah', 'Musnah')], max_length=10, verbose_name='Jenis Pelepasan')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Quantity Dilepas')),
                ('harga_jual', models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Harga Jual')),
                ('perolehan_dilepas', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=19)),
                ('akumulasi_dilepas', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=19)),
                ('residu_dilepas', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=19)),
                ('laba_rugi', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=19)),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('akun_kas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposal_kas', to='master_data.akun', verbose_name='Akun Kas/Piutang')),
                ('akun_laba_rugi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposal_laba_rugi', to='master_data.akun', verbose_name='Akun Laba/Rugi Pelepasan')),
                ('aset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to='aset_tetap.asettetaprecord', verbose_name='Aset')),
                ('jurnal_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jurnal.jurnalheader')),
            ],
            options={
                'verbose_name': 'Pelepasan Aset',
                'verbose_name_plural': 'Pelepasan Aset',
                'ordering': ['-tanggal', '-created_at'],
                'indexes': [models.Index(fields=['aset', 'tanggal'], name='idx_disposal_aset_tgl')],
            },
        ),
    ]
