# Generated by Django 6.0.6 on 2026-07-23 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset_tetap', '0004_fondasi_fase7'),
        ('jurnal', '0003_add_jurnal_terhapus_and_persentase'),
        ('master_data', '0002_akun_is_kas_setara'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Nomor Maintenance')),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Tanggal')),
                ('jenis', models.CharField(choices=[('rutin', 'Rutin'), ('perbaikan', 'Perbaikan'), ('servis', 'Servis')], max_length=10, verbose_name='Jenis')),
                ('vendor', models.CharField(blank=True, max_length=255, verbose_name='Vendor')),
                ('biaya', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Biaya')),
                ('kondisi_setelah', models.CharField(blank=True, choices=[('baik', 'Baik'), ('rusak_ringan', 'Rusak Ringan'), ('rusak_berat', 'Rusak Berat'), ('dalam_perbaikan', 'Dalam Perbaikan')], max_length=20, verbose_name='Kondisi Setelah')),
                ('kondisi_sebelum', models.CharField(blank=True, editable=False, max_length=20)),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('akun_beban', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mtn_beban', to='master_data.akun', verbose_name='Akun Beban Pemeliharaan')),
                ('akun_kas_utang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mtn_kas', to='master_data.akun', verbose_name='Akun Kas/Utang')),
                ('aset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to='aset_tetap.asettetaprecord', verbose_name='Aset')),
                ('jurnal_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jurnal.jurnalheader')),
            ],
            options={
                'verbose_name': 'Maintenance Aset',
                'verbose_name_plural': 'Maintenance Aset',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
    ]
