# Generated by Django 6.0.6 on 2026-07-23 14:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset_tetap', '0005_assetmaintenance'),
        ('entitas_bisnis', '0003_add_standar_akuntansi'),
        ('jurnal', '0003_add_jurnal_terhapus_and_persentase'),
        ('master_data', '0002_akun_is_kas_setara'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Nomor Transfer')),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Tanggal')),
                ('jenis', models.CharField(choices=[('intra_eb', 'Dalam Entitas'), ('antar_eb', 'Antar Entitas')], max_length=10, verbose_name='Jenis')),
                ('pic_lama', models.CharField(blank=True, max_length=255)),
                ('pic_baru', models.CharField(blank=True, max_length=255)),
                ('perolehan', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=19)),
                ('akumulasi', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=19)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('akun_akumulasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_akum', to='master_data.akun', verbose_name='Akun Akumulasi Penyusutan')),
                ('akun_antar_entitas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_antar', to='master_data.akun', verbose_name='Akun Antar-Entitas')),
                ('aset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='aset_tetap.asettetaprecord', verbose_name='Aset')),
                ('dept_asal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_asal', to='entitas_bisnis.entitasbisnislv3')),
                ('dept_tujuan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_tujuan', to='entitas_bisnis.entitasbisnislv3')),
                ('eb_asal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_asal', to='entitas_bisnis.entitasbisnis')),
                ('eb_tujuan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_tujuan', to='entitas_bisnis.entitasbisnis')),
                ('jurnal_header_asal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jurnal.jurnalheader')),
                ('jurnal_header_tujuan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jurnal.jurnalheader')),
                ('lokasi_asal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_asal', to='aset_tetap.lokasiaset')),
                ('lokasi_tujuan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_tujuan', to='aset_tetap.lokasiaset')),
            ],
            options={
                'verbose_name': 'Transfer Aset',
                'verbose_name_plural': 'Transfer Aset',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
    ]
