# Generated by Django 6.0.6 on 2026-07-23 14:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset_tetap', '0006_assettransfer'),
        ('jurnal', '0003_add_jurnal_terhapus_and_persentase'),
        ('master_data', '0002_akun_is_kas_setara'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRevaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revaluation_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Nomor Revaluasi')),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Tanggal')),
                ('nilai_wajar_baru', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Nilai Wajar Baru')),
                ('metode_revaluasi', models.CharField(choices=[('eliminasi', 'Eliminasi Akumulasi'), ('proporsional', 'Restatement Proporsional')], max_length=15, verbose_name='Metode Revaluasi')),
                ('perolehan_lama', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=19)),
                ('akumulasi_lama', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=19)),
                ('nilai_buku_lama', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=19)),
                ('perolehan_baru', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=19)),
                ('akumulasi_baru', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=19)),
                ('selisih', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=19)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('akun_akumulasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rev_akum', to='master_data.akun', verbose_name='Akun Akumulasi Penyusutan')),
                ('akun_rugi_revaluasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rev_rugi', to='master_data.akun', verbose_name='Akun Rugi Revaluasi')),
                ('akun_surplus_revaluasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rev_surplus', to='master_data.akun', verbose_name='Akun Surplus Revaluasi')),
                ('aset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revaluations', to='aset_tetap.asettetaprecord', verbose_name='Aset')),
                ('jurnal_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jurnal.jurnalheader')),
            ],
            options={
                'verbose_name': 'Revaluasi Aset',
                'verbose_name_plural': 'Revaluasi Aset',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
    ]
