# Generated by Django 6.0.4 on 2026-05-07 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos_catalog', '0001_initial'),
        ('pos_config', '0002_merchant_accounting_fields'),
        ('pos_crm', '0001_initial'),
        ('pos_orders', '0003_order_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('campaign_type', models.CharField(choices=[('DISCOUNT_PCT', 'Diskon %'), ('DISCOUNT_FIXED', 'Diskon Nominal'), ('BUY_X_GET_Y', 'Beli X Gratis Y'), ('FREE_ITEM', 'Item Gratis'), ('VOUCHER', 'Voucher')], max_length=30)),
                ('discount_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_discount_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('buy_quantity', models.IntegerField(blank=True, null=True)),
                ('get_quantity', models.IntegerField(blank=True, null=True)),
                ('applicable_to', models.CharField(choices=[('ALL', 'Semua'), ('CATEGORY', 'Kategori'), ('PRODUCT', 'Produk')], default='ALL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('uses_count', models.IntegerField(default=0)),
                ('per_member_limit', models.IntegerField(blank=True, null=True)),
                ('requires_member', models.BooleanField(default=False)),
                ('min_tier', models.CharField(blank=True, max_length=20)),
                ('applicable_categories', models.ManyToManyField(blank=True, to='pos_catalog.poscategory')),
                ('applicable_products', models.ManyToManyField(blank=True, to='pos_catalog.posproduct')),
                ('merchant_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='pos_config.merchantposconfig')),
                ('stores', models.ManyToManyField(blank=True, to='pos_config.storeposconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='pos_promotions.campaign')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_crm.member')),
                ('used_in_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(max_length=200)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos_promotions.campaign')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='pos_orders.order')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_promotions.voucher')),
            ],
        ),
    ]
