# Generated by Django 6.0.4 on 2026-05-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_promotions', '0001_initial'),
        ('purchase', '0003_add_nilai_residu_to_item_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='applicable_categories',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, related_name='campaign_products', to='purchase.itemmasterpurchase'),
        ),
    ]
