# Generated by Django 6.0.4 on 2026-04-15 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipeEntitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tipe Entitas',
                'verbose_name_plural': 'Tipe Entitas',
            },
        ),
        migrations.CreateModel(
            name='EntitasBisnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('relasi', models.CharField(choices=[('pelanggan', 'Pelanggan'), ('pemasok', 'Pemasok'), ('keduanya', 'Keduanya')], default='pelanggan', max_length=50, verbose_name='Relasi Bisnis')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telepon', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat_lengkap', models.TextField(blank=True, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tanggal_bergabung', models.DateField(blank=True, null=True)),
                ('status_aktif', models.BooleanField(default=True)),
                ('users', models.ManyToManyField(blank=True, related_name='entitas_bisnis_owned', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
                ('tipe_entitas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitas_bisnis_set', to='entitas_bisnis.tipeentitas', verbose_name='Tipe Entitas')),
            ],
            options={
                'verbose_name': 'Entitas Bisnis Level 1',
                'verbose_name_plural': 'Entitas Bisnis Level 1',
            },
        ),
        migrations.CreateModel(
            name='EntitasBisnisLv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telepon', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat_lengkap', models.TextField(blank=True, null=True)),
                ('tanggal_bergabung', models.DateField(blank=True, null=True)),
                ('status_aktif', models.BooleanField(default=True)),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_lv2', to='entitas_bisnis.entitasbisnis', verbose_name='Entitas Bisnis Level 1')),
            ],
            options={
                'verbose_name': 'Entitas Bisnis Level 2',
                'verbose_name_plural': 'Entitas Bisnis Level 2',
            },
        ),
        migrations.CreateModel(
            name='EntitasBisnisLv3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telepon', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat_lengkap', models.TextField(blank=True, null=True)),
                ('tanggal_bergabung', models.DateField(blank=True, null=True)),
                ('status_aktif', models.BooleanField(default=True)),
                ('parent_lv2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_lv3', to='entitas_bisnis.entitasbisnislv2', verbose_name='Entitas Bisnis Level 2')),
            ],
            options={
                'verbose_name': 'Entitas Bisnis Level 3',
                'verbose_name_plural': 'Entitas Bisnis Level 3',
            },
        ),
        migrations.AddIndex(
            model_name='entitasbisnislv2',
            index=models.Index(fields=['entitas_bisnis', 'status_aktif'], name='idx_eblv2_entitas_aktif'),
        ),
        migrations.AddIndex(
            model_name='entitasbisnislv3',
            index=models.Index(fields=['parent_lv2', 'status_aktif'], name='idx_eblv3_parent_aktif'),
        ),
        migrations.AddIndex(
            model_name='entitasbisnis',
            index=models.Index(fields=['status_aktif', 'nama'], name='idx_eb_aktif_nama'),
        ),
        migrations.AddIndex(
            model_name='entitasbisnis',
            index=models.Index(fields=['tipe_entitas', 'status_aktif'], name='idx_eb_tipe_aktif'),
        ),
    ]
