# Generated by Django 6.0.4 on 2026-04-10 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitasBisnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('tipe_entitas', models.CharField(choices=[('pelanggan', 'Pelanggan'), ('pemasok', 'Pemasok'), ('keduanya', 'Keduanya')], max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telepon', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat_lengkap', models.TextField(blank=True, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tanggal_bergabung', models.DateField(blank=True, null=True)),
                ('status_aktif', models.BooleanField(default=True)),
                ('users', models.ManyToManyField(blank=True, related_name='entitas_bisnis_set', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Entitas Bisnis',
                'verbose_name_plural': 'Entitas Bisnis',
            },
        ),
    ]
