# Generated by Django 6.0.4 on 2026-05-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitasbisnis',
            name='is_company_profile',
            field=models.BooleanField(default=False, help_text='Tandai sebagai profil perusahaan penerbit invoice/struk. Hanya satu entitas yang bisa ditandai.', verbose_name='Profil Perusahaan (Invoice)'),
        ),
    ]
