# Generated by Django 6.0.4 on 2026-04-10 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_tipe_entitas_data(apps, schema_editor):
    """Convert existing CharField tipe_entitas values into TipeEntitas FK rows."""
    EntitasBisnis = apps.get_model('entitas_bisnis', 'EntitasBisnis')
    TipeEntitas = apps.get_model('entitas_bisnis', 'TipeEntitas')

    # Collect distinct old values and create TipeEntitas rows for them.
    old_values = (
        EntitasBisnis.objects.values_list('tipe_entitas_old', flat=True)
        .distinct()
    )
    tipe_map: dict[str, object] = {}
    for val in old_values:
        if val:
            obj, _ = TipeEntitas.objects.get_or_create(nama=val)
            tipe_map[val] = obj

    for eb in EntitasBisnis.objects.all():
        if eb.tipe_entitas_old and eb.tipe_entitas_old in tipe_map:
            eb.tipe_entitas_new = tipe_map[eb.tipe_entitas_old]
            # Also copy the old tipe value into the new relasi field.
            eb.relasi = eb.tipe_entitas_old
            eb.save(update_fields=['tipe_entitas_new', 'relasi'])


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Create the TipeEntitas lookup table.
        migrations.CreateModel(
            name='TipeEntitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tipe Entitas',
                'verbose_name_plural': 'Tipe Entitas',
            },
        ),
        # 2. Add the relasi CharField (the old tipe_entitas role).
        migrations.AddField(
            model_name='entitasbisnis',
            name='relasi',
            field=models.CharField(choices=[('pelanggan', 'Pelanggan'), ('pemasok', 'Pemasok'), ('keduanya', 'Keduanya')], default='pelanggan', max_length=50, verbose_name='Relasi Bisnis'),
        ),
        # 3. Fix users related_name.
        migrations.AlterField(
            model_name='entitasbisnis',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='entitas_bisnis_owned', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        # 4. Create the CabangEntitasBisnis table.
        migrations.CreateModel(
            name='CabangEntitasBisnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telepon', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat_lengkap', models.TextField(blank=True, null=True)),
                ('tanggal_bergabung', models.DateField(blank=True, null=True)),
                ('status_aktif', models.BooleanField(default=True)),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabang_set', to='entitas_bisnis.entitasbisnis', verbose_name='Entitas Bisnis')),
            ],
            options={
                'verbose_name': 'Cabang Entitas Bisnis',
                'verbose_name_plural': 'Cabang Entitas Bisnis',
            },
        ),
        # 5. Rename old CharField tipe_entitas → tipe_entitas_old.
        migrations.RenameField(
            model_name='entitasbisnis',
            old_name='tipe_entitas',
            new_name='tipe_entitas_old',
        ),
        # 6. Add new FK field (nullable initially for data migration).
        migrations.AddField(
            model_name='entitasbisnis',
            name='tipe_entitas_new',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entitas_bisnis.tipeentitas'),
        ),
        # 7. Data migration: copy old values into TipeEntitas and set FK.
        migrations.RunPython(migrate_tipe_entitas_data, migrations.RunPython.noop),
        # 8. Remove old CharField.
        migrations.RemoveField(
            model_name='entitasbisnis',
            name='tipe_entitas_old',
        ),
        # 9. Rename new FK → tipe_entitas and make it non-nullable.
        migrations.RenameField(
            model_name='entitasbisnis',
            old_name='tipe_entitas_new',
            new_name='tipe_entitas',
        ),
        migrations.AlterField(
            model_name='entitasbisnis',
            name='tipe_entitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitas_bisnis_set', to='entitas_bisnis.tipeentitas', verbose_name='Tipe Entitas'),
        ),
    ]
