# Generated by Django 6.0.6 on 2026-06-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0002_is_company_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitasbisnis',
            name='standar_akuntansi',
            field=models.CharField(choices=[('psak', 'PSAK (PSAK 71 / Full IFRS)'), ('sak_ep', 'SAK EP (Entitas Privat)'), ('sak_emkm', 'SAK EMKM (Entitas Mikro, Kecil, Menengah)')], default='psak', help_text='Standar yang digunakan entitas ini untuk laporan keuangan.', max_length=10, verbose_name='Standar Akuntansi'),
        ),
    ]
