# Generated by Django 6.0.4 on 2026-04-10 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0002_tipeentitas_entitasbisnis_relasi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cabangentitasbisnis',
            index=models.Index(fields=['entitas_bisnis', 'status_aktif'], name='idx_cab_entitas_aktif'),
        ),
        migrations.AddIndex(
            model_name='entitasbisnis',
            index=models.Index(fields=['status_aktif', 'nama'], name='idx_eb_aktif_nama'),
        ),
        migrations.AddIndex(
            model_name='entitasbisnis',
            index=models.Index(fields=['tipe_entitas', 'status_aktif'], name='idx_eb_tipe_aktif'),
        ),
    ]
