# Generated by Django 6.0.4 on 2026-04-13 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0003_cabangentitasbisnis_idx_cab_entitas_aktif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitasBisnisLv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telepon', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat_lengkap', models.TextField(blank=True, null=True)),
                ('tanggal_bergabung', models.DateField(blank=True, null=True)),
                ('status_aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Entitas Bisnis Level 2',
                'verbose_name_plural': 'Entitas Bisnis Level 2',
            },
        ),
        migrations.CreateModel(
            name='EntitasBisnisLv3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telepon', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat_lengkap', models.TextField(blank=True, null=True)),
                ('tanggal_bergabung', models.DateField(blank=True, null=True)),
                ('status_aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Entitas Bisnis Level 3',
                'verbose_name_plural': 'Entitas Bisnis Level 3',
            },
        ),
        migrations.RemoveIndex(
            model_name='cabangentitasbisnis',
            name='idx_cab_entitas_aktif',
        ),
        migrations.AlterModelOptions(
            name='entitasbisnis',
            options={'verbose_name': 'Entitas Bisnis Level 1', 'verbose_name_plural': 'Entitas Bisnis Level 1'},
        ),
        migrations.AddField(
            model_name='entitasbisnislv2',
            name='entitas_bisnis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_lv2', to='entitas_bisnis.entitasbisnis', verbose_name='Entitas Bisnis Level 1'),
        ),
        migrations.AddField(
            model_name='entitasbisnislv3',
            name='parent_lv2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_lv3', to='entitas_bisnis.entitasbisnislv2', verbose_name='Entitas Bisnis Level 2'),
        ),
        migrations.RemoveField(
            model_name='cabangentitasbisnis',
            name='entitas_bisnis',
        ),
        migrations.AddIndex(
            model_name='entitasbisnislv2',
            index=models.Index(fields=['entitas_bisnis', 'status_aktif'], name='idx_eblv2_entitas_aktif'),
        ),
        migrations.AddIndex(
            model_name='entitasbisnislv3',
            index=models.Index(fields=['parent_lv2', 'status_aktif'], name='idx_eblv3_parent_aktif'),
        ),
        migrations.DeleteModel(
            name='CabangEntitasBisnis',
        ),
    ]
