# Generated by Django 6.0.4 on 2026-06-08 13:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitas_bisnis', '0002_is_company_profile'),
        ('master_data', '0001_initial'),
        ('purchase', '0006_add_pendapatan_module_choice'),
        ('sales', '0007_salesheader_payment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Recurring Template',
                'verbose_name_plural': 'Recurring Template',
            },
        ),
        migrations.CreateModel(
            name='PendapatanHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=100, unique=True, verbose_name='ID Transaksi')),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Tanggal')),
                ('deskripsi', models.TextField(blank=True, default='', verbose_name='Deskripsi')),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('from_sales', 'Dari Sales'), ('recurring', 'Recurring')], default='manual', max_length=20, verbose_name='Sumber')),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Kredit')], default='cash', max_length=10, verbose_name='Tipe Pembayaran')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Dikonfirmasi'), ('voided', 'Dibatalkan')], default='draft', max_length=20, verbose_name='Status')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Terkunci')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendapatan_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('source_sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendapatan_headers', to='sales.salesheader', verbose_name='Sales Header')),
                ('source_recurring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_headers', to='pendapatan.recurringtemplate', verbose_name='Recurring Template')),
            ],
            options={
                'verbose_name': 'Pendapatan Header',
                'verbose_name_plural': 'Pendapatan Header',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendapatanEntitasBisnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendapatan_groups', to='entitas_bisnis.entitasbisnis', verbose_name='Entitas Bisnis')),
                ('entitas_bisnis_lv2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendapatan_groups', to='entitas_bisnis.entitasbisnislv2', verbose_name='EB Lv2')),
                ('entitas_bisnis_lv3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendapatan_groups', to='entitas_bisnis.entitasbisnislv3', verbose_name='EB Lv3')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendapatan_eb_payment', to='master_data.akun', verbose_name='Akun Pembayaran')),
                ('pendapatan_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitas_groups', to='pendapatan.pendapatanheader', verbose_name='Pendapatan Header')),
            ],
            options={
                'verbose_name': 'Pendapatan Entitas Bisnis',
                'verbose_name_plural': 'Pendapatan Entitas Bisnis',
            },
        ),
        migrations.CreateModel(
            name='PendapatanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi_item', models.TextField(verbose_name='Deskripsi Item')),
                ('kategori', models.CharField(choices=[('sewa', 'Sewa'), ('jasa', 'Jasa'), ('bunga', 'Bunga'), ('dividen', 'Dividen'), ('komisi', 'Komisi'), ('royalti', 'Royalti'), ('management_fee', 'Management Fee'), ('penjualan_aset', 'Penjualan Aset'), ('lainnya', 'Lainnya')], max_length=30, verbose_name='Kategori')),
                ('jumlah_bruto', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Jumlah Bruto')),
                ('tax', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='Pajak (Nominal)')),
                ('tax_type', models.CharField(blank=True, choices=[('ppn_keluaran', 'PPN Keluaran'), ('pph_23', 'PPh 23'), ('pph_21', 'PPh 21'), ('pph_4_2', 'PPh 4(2)')], default='', max_length=30, verbose_name='Tipe Pajak')),
                ('tax_payment', models.CharField(blank=True, choices=[('belum_transfer', 'Belum Transfer'), ('sudah_transfer', 'Sudah Transfer')], default='', max_length=20, verbose_name='Status Transfer Pajak')),
                ('is_deferred', models.BooleanField(default=False, verbose_name='Pendapatan Diterima di Muka')),
                ('deferred_tanggal_mulai', models.DateField(blank=True, null=True, verbose_name='Tanggal Mulai Pengakuan')),
                ('deferred_tanggal_selesai', models.DateField(blank=True, null=True, verbose_name='Tanggal Selesai Pengakuan')),
                ('deferred_metode', models.CharField(blank=True, choices=[('straight_line', 'Garis Lurus'), ('custom', 'Custom')], default='straight_line', max_length=20, verbose_name='Metode Pengakuan')),
                ('deferred_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendapatan_item_deferred', to='master_data.akun', verbose_name='Akun Deferred (Liability)')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendapatan_item_payment', to='master_data.akun', verbose_name='Akun Pembayaran')),
                ('pendapatan_eb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pendapatan.pendapatanentitasbisnis', verbose_name='Pendapatan EB Group')),
                ('recognition_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendapatan_item_recognition', to='master_data.akun', verbose_name='Akun Pengakuan')),
                ('revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendapatan_item_revenue', to='master_data.akun', verbose_name='Akun Pendapatan')),
                ('sub_transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendapatan_items', to='purchase.subtransactiontype', verbose_name='Sub-Tipe Transaksi')),
                ('tax_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendapatan_item_tax', to='master_data.akun', verbose_name='Akun Pajak')),
                ('tax_payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendapatan_item_tax_payment', to='master_data.akun', verbose_name='Akun Utang Pajak')),
            ],
            options={
                'verbose_name': 'Pendapatan Item',
                'verbose_name_plural': 'Pendapatan Item',
            },
        ),
        migrations.CreateModel(
            name='PendapatanEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Dibuat'), ('CONFIRMED', 'Dikonfirmasi'), ('VOIDED', 'Dibatalkan'), ('JOURNAL_CREATED', 'Jurnal Dibuat'), ('PIUTANG_CREATED', 'Piutang Dibuat'), ('DEFERRED_SCHEDULED', 'Deferred Dijadwalkan'), ('RECURRING_GENERATED', 'Dihasilkan dari Recurring')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendapatan_event_logs', to=settings.AUTH_USER_MODEL)),
                ('pendapatan_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='pendapatan.pendapatanheader', verbose_name='Pendapatan Header')),
            ],
            options={
                'verbose_name': 'Event Log Pendapatan',
                'verbose_name_plural': 'Event Log Pendapatan',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['pendapatan_header', 'timestamp'], name='idx_pel_header_ts')],
            },
        ),
        migrations.AddIndex(
            model_name='pendapatanentitasbisnis',
            index=models.Index(fields=['pendapatan_header', 'entitas_bisnis'], name='idx_pend_eb_header_eb'),
        ),
        migrations.AddIndex(
            model_name='pendapatanitem',
            index=models.Index(fields=['pendapatan_eb'], name='idx_pend_pi_eb'),
        ),
        migrations.AddIndex(
            model_name='pendapatanitem',
            index=models.Index(fields=['sub_transaction_type'], name='idx_pend_pi_stt'),
        ),
        migrations.AddIndex(
            model_name='pendapatanheader',
            index=models.Index(fields=['tanggal', 'status'], name='idx_pendh_tanggal_status'),
        ),
    ]
