# Generated by Django 6.0.4 on 2026-06-09 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0003_add_jurnal_terhapus_and_persentase'),
        ('master_data', '0001_initial'),
        ('pendapatan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeferredRevenueSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_total', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Jumlah Total')),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai')),
                ('tanggal_selesai', models.DateField(verbose_name='Tanggal Selesai')),
                ('metode', models.CharField(choices=[('straight_line', 'Garis Lurus'), ('custom', 'Custom')], default='straight_line', max_length=20, verbose_name='Metode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deferred_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deferred_liability', to='master_data.akun', verbose_name='Akun Deferred (Liability)')),
                ('pendapatan_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deferred_schedule', to='pendapatan.pendapatanitem', verbose_name='Pendapatan Item')),
                ('recognition_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deferred_recognition', to='master_data.akun', verbose_name='Akun Pengakuan')),
            ],
            options={
                'verbose_name': 'Jadwal Deferred Revenue',
                'verbose_name_plural': 'Jadwal Deferred Revenue',
            },
        ),
        migrations.CreateModel(
            name='DeferredRevenueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField(verbose_name='Periode (1 = bulan)')),
                ('jumlah', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Jumlah')),
                ('status', models.CharField(choices=[('pending', 'Belum Diakui'), ('recognized', 'Sudah Diakui'), ('reversed', 'Dibalik')], default='pending', max_length=20, verbose_name='Status')),
                ('jurnal_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_entries', to='jurnal.jurnalheader', verbose_name='Jurnal')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='pendapatan.deferredrevenueschedule', verbose_name='Jadwal')),
            ],
            options={
                'verbose_name': 'Entry Deferred Revenue',
                'verbose_name_plural': 'Entry Deferred Revenue',
                'ordering': ['periode'],
                'unique_together': {('schedule', 'periode')},
            },
        ),
    ]
