# Generated by Django 6.0.4 on 2026-06-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendapatan', '0003_recurring_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
