# Generated by Django 6.0.6 on 2026-06-18 11:18

from decimal import Decimal
from django.db import migrations


def migrate_deferred_to_jadwal(apps, schema_editor):
    DeferredRevenueSchedule = apps.get_model('pendapatan', 'DeferredRevenueSchedule')
    DeferredRevenueEntry = apps.get_model('pendapatan', 'DeferredRevenueEntry')
    JadwalPengakuan = apps.get_model('pendapatan', 'JadwalPengakuan')
    EntriPengakuan = apps.get_model('pendapatan', 'EntriPengakuan')
    KewajibabPelaksanaan = apps.get_model('pendapatan', 'KewajibabPelaksanaan')

    # Set recognition_type based on is_deferred
    KewajibabPelaksanaan.objects.filter(is_deferred=True).update(recognition_type='over_time')
    KewajibabPelaksanaan.objects.filter(is_deferred=False).update(recognition_type='point_in_time')

    METODE_MAP = {'straight_line': 'straight_line', 'custom': 'milestone'}
    STATUS_MAP = {'pending': 'pending', 'recognized': 'recognized', 'reversed': 'skipped'}

    for drs in DeferredRevenueSchedule.objects.prefetch_related('entries').all():
        entries = list(drs.entries.all())

        # Compute nilai_diakui as sum of recognized entries
        nilai_diakui = sum(
            e.jumlah for e in entries if e.status == 'recognized'
        ) or Decimal('0')

        # Determine jadwal status
        all_recognized = all(e.status == 'recognized' for e in entries) if entries else False
        jadwal_status = 'completed' if all_recognized else 'active'

        jadwal = JadwalPengakuan.objects.create(
            kp_id=drs.pendapatan_item_id,
            tipe_aliran='advance_payment_cash',
            progress_method=METODE_MAP.get(drs.metode, 'straight_line'),
            tanggal_mulai=drs.tanggal_mulai,
            tanggal_selesai=drs.tanggal_selesai,
            liabilitas_kontrak_acct_id=drs.deferred_account_id,
            nilai_total=drs.jumlah_total,
            nilai_diakui=nilai_diakui,
            status=jadwal_status,
        )

        for entry in entries:
            EntriPengakuan.objects.create(
                jadwal=jadwal,
                tanggal_target=entry.periode,
                nilai=entry.jumlah,
                nilai_diakui=entry.jumlah if entry.status == 'recognized' else Decimal('0'),
                status=STATUS_MAP.get(entry.status, 'pending'),
                jurnal_header_id=entry.jurnal_header_id,
            )


def reverse_migrate(apps, schema_editor):
    JadwalPengakuan = apps.get_model('pendapatan', 'JadwalPengakuan')
    EntriPengakuan = apps.get_model('pendapatan', 'EntriPengakuan')
    EntriPengakuan.objects.all().delete()
    JadwalPengakuan.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pendapatan', '0005_psak72_schema'),
    ]

    operations = [
        migrations.RunPython(migrate_deferred_to_jadwal, reverse_code=reverse_migrate),
    ]
