# Generated by Django 6.0.6 on 2026-06-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendapatan', '0006_psak72_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deferredrevenueschedule',
            name='deferred_account',
        ),
        migrations.RemoveField(
            model_name='deferredrevenueschedule',
            name='pendapatan_item',
        ),
        migrations.RemoveField(
            model_name='deferredrevenueschedule',
            name='recognition_account',
        ),
        migrations.AlterModelOptions(
            name='kewajibabpelaksanaan',
            options={'verbose_name': 'Kewajiban Pelaksanaan', 'verbose_name_plural': 'Kewajiban Pelaksanaan'},
        ),
        migrations.RemoveField(
            model_name='kewajibabpelaksanaan',
            name='deferred_account',
        ),
        migrations.RemoveField(
            model_name='kewajibabpelaksanaan',
            name='deferred_metode',
        ),
        migrations.RemoveField(
            model_name='kewajibabpelaksanaan',
            name='deferred_tanggal_mulai',
        ),
        migrations.RemoveField(
            model_name='kewajibabpelaksanaan',
            name='deferred_tanggal_selesai',
        ),
        migrations.RemoveField(
            model_name='kewajibabpelaksanaan',
            name='is_deferred',
        ),
        migrations.RemoveField(
            model_name='kewajibabpelaksanaan',
            name='recognition_account',
        ),
        migrations.AlterField(
            model_name='kewajibabpelaksanaan',
            name='nilai_kontrak',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Nilai Kontrak'),
        ),
        migrations.AlterField(
            model_name='pendapataneventlog',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Dibuat'), ('CONFIRMED', 'Dikonfirmasi'), ('VOIDED', 'Dibatalkan'), ('JOURNAL_CREATED', 'Jurnal Dibuat'), ('PIUTANG_CREATED', 'Piutang Dibuat'), ('DEFERRED_SCHEDULED', 'Deferred Dijadwalkan'), ('RECURRING_GENERATED', 'Dihasilkan dari Recurring'), ('RECOGNIZE', 'Pengakuan Pendapatan'), ('JOURNAL_PSAK72', 'Jurnal PSAK 72 Dibuat'), ('PIUTANG_CREATED_KP', 'Piutang KP Dibuat'), ('ASSET_CONVERTED', 'Aset Kontrak Dikonversi'), ('JADWAL_CREATED', 'Jadwal Pengakuan Dibuat')], max_length=30),
        ),
        migrations.DeleteModel(
            name='DeferredRevenueEntry',
        ),
        migrations.DeleteModel(
            name='DeferredRevenueSchedule',
        ),
    ]
