# Generated by Django 6.0.6 on 2026-06-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendapatan', '0008_kp_tax_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='kptaxline',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='True jika nominal pajak diisi/diubah manual oleh user. False berarti nominal dihitung ulang dari tarif saat konfirmasi.', verbose_name='Override Manual'),
        ),
        migrations.AlterField(
            model_name='kptaxline',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Nominal pajak. Hasil hitung otomatis atau override manual (lihat is_manual).', max_digits=19, null=True, verbose_name='Pajak (Nominal)'),
        ),
    ]
