# Generated by Django 6.0.6 on 2026-06-20 16:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('pendapatan', '0009_kptaxline_is_manual_alter_kptaxline_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendapatanPiutangProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debitur', models.CharField(blank=True, default='', max_length=255, verbose_name='Debitur')),
                ('jatuh_tempo', models.DateField(blank=True, null=True, verbose_name='Jatuh Tempo')),
                ('jenis_jangka_waktu', models.CharField(default='short_term', max_length=20, verbose_name='Jenis Jangka Waktu')),
                ('jenis_bunga', models.CharField(default='tanpa_bunga', max_length=20, verbose_name='Jenis Bunga')),
                ('suku_bunga', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Suku Bunga')),
                ('periode_angsuran', models.CharField(default='bulanan', max_length=20, verbose_name='Periode Angsuran')),
                ('pv_discount_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Market Rate PV')),
                ('standar_akuntansi', models.CharField(blank=True, default='', max_length=10, verbose_name='Standar Akuntansi')),
                ('kategori_pengukuran', models.CharField(default='amortised_cost', max_length=20, verbose_name='Kategori Pengukuran')),
                ('business_model', models.CharField(blank=True, default='', max_length=30, verbose_name='Business Model')),
                ('sppi_test_passed', models.BooleanField(blank=True, null=True, verbose_name='SPPI Test Lulus')),
                ('biaya_transaksi', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19, verbose_name='Biaya Transaksi')),
                ('agunan_jenis', models.CharField(blank=True, default='', max_length=255, verbose_name='Jenis Agunan')),
                ('agunan_nilai', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='Nilai Agunan')),
                ('is_approval_required', models.BooleanField(default=False, verbose_name='Perlu Approval')),
                ('biaya_transaksi_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendapatan_profil_biaya', to='master_data.akun', verbose_name='Akun Biaya Transaksi')),
                ('coa_piutang_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendapatan_profil_piutang', to='master_data.akun', verbose_name='Akun Piutang')),
                ('coa_piutang_lancar_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendapatan_profil_lancar', to='master_data.akun', verbose_name='Akun Piutang Bagian Lancar')),
                ('interest_income_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendapatan_profil_interest', to='master_data.akun', verbose_name='Akun Pendapatan Bunga Efektif')),
                ('pendapatan_header', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='piutang_profil', to='pendapatan.pendapatanheader', verbose_name='Pendapatan Header')),
            ],
            options={
                'verbose_name': 'Profil Piutang Pendapatan',
                'verbose_name_plural': 'Profil Piutang Pendapatan',
            },
        ),
    ]
