# Generated by Django 6.0.6 on 2026-06-18 17:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitas_bisnis', '0003_add_standar_akuntansi'),
        ('jurnal', '0003_add_jurnal_terhapus_and_persentase'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BracketPPhOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batas_bawah', models.DecimalField(decimal_places=0, max_digits=19)),
                ('batas_atas', models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True)),
                ('tarif_persen', models.DecimalField(decimal_places=2, max_digits=5)),
                ('berlaku_mulai', models.DateField()),
            ],
            options={
                'verbose_name': 'Bracket PPh OP',
                'verbose_name_plural': 'Bracket PPh OP',
                'ordering': ['berlaku_mulai', 'batas_bawah'],
            },
        ),
        migrations.CreateModel(
            name='MasaPajak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveSmallIntegerField()),
                ('bulan', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('locked', 'Locked')], default='open', max_length=10)),
            ],
            options={
                'verbose_name': 'Masa Pajak',
                'verbose_name_plural': 'Masa Pajak',
                'ordering': ['-tahun', '-bulan'],
                'unique_together': {('tahun', 'bulan')},
            },
        ),
        migrations.CreateModel(
            name='TarifPajak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_pajak', models.CharField(choices=[('ppn_umum', 'PPN Umum (BKP/JKP non-mewah)'), ('ppn_mewah', 'PPN Mewah (BKP Mewah 12%)'), ('ppn_ekspor', 'PPN Ekspor (0%)'), ('ppn_bm', 'PPnBM'), ('pph_23_jasa', 'PPh 23 Jasa (2%)'), ('pph_23_royalti', 'PPh 23 Royalti (15%)'), ('pph_23_dividen', 'PPh 23 Dividen (15%)'), ('pph_21_bukan_pegawai', 'PPh 21 Bukan Pegawai (progresif)'), ('pph_4_2_sewa', 'PPh 4(2) Sewa Tanah/Bangunan (10%)'), ('pph_4_2_bunga', 'PPh 4(2) Bunga Deposito (20%)'), ('pph_umkm', 'PPh Final UMKM (0,5%)')], db_index=True, max_length=40)),
                ('nama', models.CharField(max_length=100)),
                ('tarif_persen', models.DecimalField(decimal_places=4, max_digits=7)),
                ('faktor_dpp', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Pengali DPP sebelum tarif diterapkan. ppn_umum (PMK 131/2024): 11/12 ≈ 0.916667', max_digits=7)),
                ('berlaku_mulai', models.DateField()),
                ('berlaku_sampai', models.DateField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tarif Pajak',
                'verbose_name_plural': 'Tarif Pajak',
                'indexes': [models.Index(fields=['jenis_pajak', 'berlaku_mulai'], name='idx_tarif_jenis_mulai')],
            },
        ),
        migrations.CreateModel(
            name='PajakTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('pendapatan_kp', 'Pendapatan — Kewajiban Pelaksanaan'), ('sales_item', 'Sales Item'), ('purchase_item', 'Purchase Item'), ('piutang_item', 'Piutang Item'), ('utang_item', 'Utang Item')], db_index=True, max_length=40)),
                ('source_id', models.PositiveIntegerField(db_index=True)),
                ('masa_pajak', models.DateField(db_index=True)),
                ('jenis_pajak', models.CharField(choices=[('ppn_umum', 'PPN Umum (BKP/JKP non-mewah)'), ('ppn_mewah', 'PPN Mewah (BKP Mewah 12%)'), ('ppn_ekspor', 'PPN Ekspor (0%)'), ('ppn_bm', 'PPnBM'), ('pph_23_jasa', 'PPh 23 Jasa (2%)'), ('pph_23_royalti', 'PPh 23 Royalti (15%)'), ('pph_23_dividen', 'PPh 23 Dividen (15%)'), ('pph_21_bukan_pegawai', 'PPh 21 Bukan Pegawai (progresif)'), ('pph_4_2_sewa', 'PPh 4(2) Sewa Tanah/Bangunan (10%)'), ('pph_4_2_bunga', 'PPh 4(2) Bunga Deposito (20%)'), ('pph_umkm', 'PPh Final UMKM (0,5%)')], max_length=40)),
                ('dpp', models.DecimalField(decimal_places=4, max_digits=19)),
                ('tarif_persen', models.DecimalField(decimal_places=4, max_digits=7)),
                ('jumlah_pajak', models.DecimalField(decimal_places=4, max_digits=19)),
                ('sifat_pajak', models.CharField(choices=[('potong_pungut', 'Potong/Pungut — Dr akun_lawan | Cr akun_pajak'), ('prepaid', 'Prepaid/Dipotong Lawan — Dr akun_pajak | Cr akun_lawan')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('disetor', 'Disetor'), ('dibatalkan', 'Dibatalkan')], default='draft', max_length=15)),
                ('is_overridden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('akun_lawan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pajak_transaksi_lawan_set', to='master_data.akun')),
                ('akun_pajak', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pajak_transaksi_pajak_set', to='master_data.akun')),
                ('entitas_bisnis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pajak_transaksi_set', to='entitas_bisnis.entitasbisnis')),
                ('jurnal_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pajak_transaksi_set', to='jurnal.jurnalheader')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pajak_transaksi_modified_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pajak Transaksi',
                'verbose_name_plural': 'Pajak Transaksi',
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='idx_pajak_trx_source'), models.Index(fields=['masa_pajak', 'jenis_pajak'], name='idx_pajak_trx_masa_jenis'), models.Index(fields=['status'], name='idx_pajak_trx_status')],
            },
        ),
    ]
