# Generated by Django 6.0.6 on 2026-07-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pajak', '0002_seed_tarif'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pajaktransaksi',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pajak Transaksi', 'verbose_name_plural': 'Pajak Transaksi'},
        ),
        migrations.AlterField(
            model_name='pajaktransaksi',
            name='source_type',
            field=models.CharField(choices=[('pendapatan_kp', 'Pendapatan — Kewajiban Pelaksanaan'), ('sales_item', 'Sales Item'), ('retur_customer_item', 'Retur Pelanggan — Item'), ('purchase_item', 'Purchase Item'), ('piutang_item', 'Piutang Item'), ('utang_item', 'Utang Item')], db_index=True, max_length=40),
        ),
    ]
