# Generated by Django 6.0.4 on 2026-04-10 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_id', models.CharField(choices=[('aset', 'Aset'), ('kewajiban', 'Kewajiban'), ('ekuitas', 'Ekuitas'), ('pendapatan', 'Pendapatan'), ('beban', 'Beban')], max_length=50)),
                ('kategori_akun', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Akun',
                'verbose_name_plural': 'Akun',
            },
        ),
        migrations.CreateModel(
            name='AsetLv1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Aset Level 1',
                'verbose_name_plural': 'Aset Level 1',
            },
        ),
        migrations.CreateModel(
            name='Bukti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referensi_eksternal', models.CharField(max_length=100)),
                ('tipe_dokumen', models.CharField(max_length=50)),
                ('filepath', models.CharField(max_length=512)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_hash', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Bukti',
                'verbose_name_plural': 'Bukti',
            },
        ),
        migrations.CreateModel(
            name='EkuitasLv1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ekuitas Level 1',
                'verbose_name_plural': 'Ekuitas Level 1',
            },
        ),
        migrations.CreateModel(
            name='KewajibanLv1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Kewajiban Level 1',
                'verbose_name_plural': 'Kewajiban Level 1',
            },
        ),
        migrations.CreateModel(
            name='TipeTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_transaksi', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipe Transaksi',
                'verbose_name_plural': 'Tipe Transaksi',
            },
        ),
        migrations.CreateModel(
            name='AsetLv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('aset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master_data.asetlv1')),
            ],
            options={
                'verbose_name': 'Aset Level 2',
                'verbose_name_plural': 'Aset Level 2',
            },
        ),
        migrations.CreateModel(
            name='EkuitasLv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('ekuitas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master_data.ekuitaslv1')),
            ],
            options={
                'verbose_name': 'Ekuitas Level 2',
                'verbose_name_plural': 'Ekuitas Level 2',
            },
        ),
        migrations.CreateModel(
            name='KewajibanLv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('kewajiban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master_data.kewajibanlv1')),
            ],
            options={
                'verbose_name': 'Kewajiban Level 2',
                'verbose_name_plural': 'Kewajiban Level 2',
            },
        ),
    ]
