# Generated by Django 6.0.4 on 2026-04-15 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitas_bisnis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsetLv1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Aset Level 1',
                'verbose_name_plural': 'Aset Level 1',
            },
        ),
        migrations.CreateModel(
            name='BebanLv1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Beban Level 1',
                'verbose_name_plural': 'Beban Level 1',
            },
        ),
        migrations.CreateModel(
            name='EkuitasLv1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ekuitas Level 1',
                'verbose_name_plural': 'Ekuitas Level 1',
            },
        ),
        migrations.CreateModel(
            name='KewajibanLv1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Kewajiban Level 1',
                'verbose_name_plural': 'Kewajiban Level 1',
            },
        ),
        migrations.CreateModel(
            name='PendapatanLv1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Pendapatan Level 1',
                'verbose_name_plural': 'Pendapatan Level 1',
            },
        ),
        migrations.CreateModel(
            name='TipeTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_transaksi', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipe Transaksi',
                'verbose_name_plural': 'Tipe Transaksi',
            },
        ),
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_id', models.CharField(choices=[('aset', 'Aset'), ('kewajiban', 'Kewajiban'), ('ekuitas', 'Ekuitas'), ('pendapatan', 'Pendapatan'), ('beban', 'Beban')], db_index=True, max_length=50)),
                ('kategori_akun', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('nama', models.CharField(blank=True, default='', max_length=255)),
                ('kode_akun', models.CharField(blank=True, db_index=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Akun',
                'verbose_name_plural': 'Akun',
                'indexes': [models.Index(fields=['kategori_id', 'kategori_akun'], name='idx_akun_kategori')],
            },
        ),
        migrations.CreateModel(
            name='AsetLv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('aset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master_data.asetlv1')),
            ],
            options={
                'verbose_name': 'Aset Level 2',
                'verbose_name_plural': 'Aset Level 2',
            },
        ),
        migrations.CreateModel(
            name='BebanLv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('beban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master_data.bebanlv1')),
            ],
            options={
                'verbose_name': 'Beban Level 2',
                'verbose_name_plural': 'Beban Level 2',
            },
        ),
        migrations.CreateModel(
            name='Bukti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referensi_eksternal', models.CharField(max_length=100)),
                ('tipe_dokumen', models.CharField(max_length=50)),
                ('filepath', models.CharField(max_length=512)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_hash', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Bukti',
                'verbose_name_plural': 'Bukti',
                'indexes': [models.Index(fields=['referensi_eksternal', 'tipe_dokumen'], name='idx_bukti_ref_tipe'), models.Index(fields=['file_hash'], name='idx_bukti_hash')],
            },
        ),
        migrations.CreateModel(
            name='EkuitasLv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('ekuitas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master_data.ekuitaslv1')),
            ],
            options={
                'verbose_name': 'Ekuitas Level 2',
                'verbose_name_plural': 'Ekuitas Level 2',
            },
        ),
        migrations.CreateModel(
            name='KewajibanLv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('kewajiban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master_data.kewajibanlv1')),
            ],
            options={
                'verbose_name': 'Kewajiban Level 2',
                'verbose_name_plural': 'Kewajiban Level 2',
            },
        ),
        migrations.CreateModel(
            name='PendapatanLv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('pendapatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master_data.pendapatanlv1')),
            ],
            options={
                'verbose_name': 'Pendapatan Level 2',
                'verbose_name_plural': 'Pendapatan Level 2',
            },
        ),
        migrations.CreateModel(
            name='EntitasBisnisAkun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitas_bisnis_links', to='master_data.akun', verbose_name='Akun')),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_akuns', to='entitas_bisnis.entitasbisnis', verbose_name='Entitas Bisnis')),
            ],
            options={
                'verbose_name': 'Entitas Bisnis Akun',
                'verbose_name_plural': 'Entitas Bisnis Akun',
                'indexes': [models.Index(fields=['entitas_bisnis', 'akun'], name='idx_eba_eb_akun')],
                'unique_together': {('entitas_bisnis', 'akun')},
            },
        ),
    ]
