# Generated by Django 6.0.4 on 2026-04-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun',
            name='kategori_akun',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='akun',
            name='kategori_id',
            field=models.CharField(choices=[('aset', 'Aset'), ('kewajiban', 'Kewajiban'), ('ekuitas', 'Ekuitas'), ('pendapatan', 'Pendapatan'), ('beban', 'Beban')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='akun',
            index=models.Index(fields=['kategori_id', 'kategori_akun'], name='idx_akun_kategori'),
        ),
        migrations.AddIndex(
            model_name='bukti',
            index=models.Index(fields=['referensi_eksternal', 'tipe_dokumen'], name='idx_bukti_ref_tipe'),
        ),
        migrations.AddIndex(
            model_name='bukti',
            index=models.Index(fields=['file_hash'], name='idx_bukti_hash'),
        ),
    ]
