# Generated by Django 6.0.4 on 2026-04-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_alter_akun_kategori_akun_alter_akun_kategori_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='akun',
            name='nama',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
