# Generated by Django 6.0.4 on 2026-04-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_akun_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='akun',
            name='kode_akun',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
    ]
