# Generated by Django 6.0.4 on 2026-04-13 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_akun_kode_akun'),
    ]

    operations = [
        migrations.CreateModel(
            name='BebanLv1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Beban Level 1',
                'verbose_name_plural': 'Beban Level 1',
            },
        ),
        migrations.CreateModel(
            name='PendapatanLv1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Pendapatan Level 1',
                'verbose_name_plural': 'Pendapatan Level 1',
            },
        ),
        migrations.CreateModel(
            name='BebanLv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('beban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master_data.bebanlv1')),
            ],
            options={
                'verbose_name': 'Beban Level 2',
                'verbose_name_plural': 'Beban Level 2',
            },
        ),
        migrations.CreateModel(
            name='PendapatanLv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('pendapatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master_data.pendapatanlv1')),
            ],
            options={
                'verbose_name': 'Pendapatan Level 2',
                'verbose_name_plural': 'Pendapatan Level 2',
            },
        ),
    ]
