# Generated by Django 6.0.4 on 2026-04-15 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0004_entitasbisnislv2_entitasbisnislv3_and_more'),
        ('master_data', '0005_bebanlv1_pendapatanlv1_bebanlv2_pendapatanlv2'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitasBisnisAkun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitas_bisnis_links', to='master_data.akun', verbose_name='Akun')),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_akuns', to='entitas_bisnis.entitasbisnis', verbose_name='Entitas Bisnis')),
            ],
            options={
                'verbose_name': 'Entitas Bisnis Akun',
                'verbose_name_plural': 'Entitas Bisnis Akun',
                'indexes': [models.Index(fields=['entitas_bisnis', 'akun'], name='idx_eba_eb_akun')],
                'unique_together': {('entitas_bisnis', 'akun')},
            },
        ),
    ]
