# Generated by Django 6.0.4 on 2026-04-10 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitas_bisnis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutasiInventoryHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dll', models.CharField(blank=True, max_length=50)),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutasi_inventory_headers', to='entitas_bisnis.entitasbisnis')),
            ],
            options={
                'verbose_name': 'Mutasi Inventory Header',
                'verbose_name_plural': 'Mutasi Inventory Header',
            },
        ),
        migrations.CreateModel(
            name='MutasiInventoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dll', models.CharField(blank=True, max_length=50)),
                ('mutasi_inventory_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.mutasiinventoryheader')),
            ],
            options={
                'verbose_name': 'Mutasi Inventory Detail',
                'verbose_name_plural': 'Mutasi Inventory Detail',
            },
        ),
    ]
