# Generated by Django 6.0.4 on 2026-04-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecord',
            name='metode_alokasi',
            field=models.CharField(blank=True, choices=[('fifo', 'FIFO (First In First Out)'), ('lifo', 'LIFO (Last In First Out)'), ('avg', 'Rata-Rata Tertimbang (Weighted Average)'), ('specific', 'Identifikasi Khusus (Specific Identification)')], default='', max_length=50, verbose_name='Metode Alokasi Biaya'),
        ),
    ]
