# Generated by Django 6.0.4 on 2026-04-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0003_cabangentitasbisnis_idx_cab_entitas_aktif_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mutasiinventoryheader',
            index=models.Index(fields=['entitas_bisnis'], name='idx_mih_entitas'),
        ),
    ]
