# Generated by Django 6.0.4 on 2026-05-12 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0002_is_company_profile'),
        ('inventory', '0002_fix_metode_alokasi_max_length'),
        ('purchase', '0003_add_nilai_residu_to_item_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrecord',
            name='entitas_bisnis_lv2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records_lv2', to='entitas_bisnis.entitasbisnislv2', verbose_name='Entitas Bisnis Lv2'),
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='entitas_bisnis_lv3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records_lv3', to='entitas_bisnis.entitasbisnislv3', verbose_name='Entitas Bisnis Lv3'),
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Harga Jual'),
        ),
        migrations.AddIndex(
            model_name='inventoryrecord',
            index=models.Index(fields=['entitas_bisnis_lv3'], name='idx_ir_lv3'),
        ),
    ]
