# Generated by Django 6.0.4 on 2026-04-14 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0004_entitasbisnislv2_entitasbisnislv3_and_more'),
        ('inventory', '0002_mutasiinventoryheader_idx_mih_entitas'),
        ('purchase', '0005_itemmasterpurchase_masa_manfaat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Inventory Number')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Unit Price')),
                ('total_value', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=19, verbose_name='Total Value')),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Tanggal')),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Lead Time (Days)')),
                ('ordering_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='Ordering Cost')),
                ('holding_cost_pct', models.DecimalField(blank=True, decimal_places=4, help_text='Contoh: 0.1 = 10%', max_digits=5, null=True, verbose_name='Holding Cost %')),
                ('moq', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='MOQ')),
                ('metode_alokasi', models.CharField(blank=True, choices=[('fifo', 'FIFO (First In First Out)'), ('lifo', 'LIFO (Last In First Out)'), ('avg', 'Rata-Rata Tertimbang (Weighted Average)'), ('specific', 'Identifikasi Khusus (Specific Identification)')], default='', max_length=20, verbose_name='Metode Alokasi Biaya')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='entitas_bisnis.entitasbisnis', verbose_name='Entitas Bisnis')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='purchase.itemmasterpurchase', verbose_name='Item Master')),
                ('purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_records', to='purchase.purchaseitem', verbose_name='Purchase Item')),
            ],
            options={
                'verbose_name': 'Inventory Record',
                'verbose_name_plural': 'Inventory Records',
                'ordering': ['-tanggal', '-created_at'],
                'indexes': [models.Index(fields=['item', 'tanggal'], name='idx_ir_item_tanggal'), models.Index(fields=['entitas_bisnis', 'tanggal'], name='idx_ir_eb_tanggal'), models.Index(fields=['inventory_number'], name='idx_ir_inv_number')],
            },
        ),
    ]
