# Generated by Django 6.0.4 on 2026-06-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryrecord_entitas_bisnis_lv2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecord',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Unit Cost'),
        ),
    ]
