# Generated by Django 6.0.4 on 2026-04-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrecord',
            name='tanggal_kadaluarsa',
            field=models.DateField(blank=True, help_text='Tanggal kadaluarsa item. Otomatis dihitung dari lama_kadaluarsa item master jika tidak diisi manual.', null=True, verbose_name='Tanggal Kadaluarsa'),
        ),
    ]
