# Generated by Django 6.0.6 on 2026-07-15 13:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('entitas_bisnis', '0003_add_standar_akuntansi'),
        ('inventory', '0004_alter_inventoryrecord_unit_price_verbose_name'),
        ('purchase', '0008_backfill_item_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(db_index=True, verbose_name='Tanggal')),
                ('movement_type', models.CharField(choices=[('purchase_in', 'Pembelian Masuk'), ('sale_out', 'Penjualan Keluar'), ('production_in', 'Produksi Masuk (FG)'), ('production_out', 'Produksi Keluar (RM)'), ('saldo_awal', 'Saldo Awal')], db_index=True, max_length=20, verbose_name='Jenis Pergerakan')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Qty (signed, base uom)')),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Biaya Satuan')),
                ('remaining_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='Sisa Qty (layer inflow)')),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='entitas_bisnis.entitasbisnis', verbose_name='Entitas Bisnis')),
                ('entitas_bisnis_lv2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements_lv2', to='entitas_bisnis.entitasbisnislv2', verbose_name='Entitas Bisnis Lv2')),
                ('entitas_bisnis_lv3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements_lv3', to='entitas_bisnis.entitasbisnislv3', verbose_name='Entitas Bisnis Lv3')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='purchase.itemmasterpurchase', verbose_name='Item')),
                ('legacy_fifo_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='purchase.fifobatch', verbose_name='FIFOBatch (mirror)')),
                ('legacy_inventory_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.inventoryrecord', verbose_name='InventoryRecord (mirror)')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['tanggal', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Qty Dialokasikan')),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Biaya Layer')),
                ('in_movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions_in', to='inventory.stockmovement', verbose_name='Layer Inflow')),
                ('out_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions_out', to='inventory.stockmovement', verbose_name='Movement Keluar')),
            ],
            options={
                'verbose_name': 'Stock Consumption',
                'verbose_name_plural': 'Stock Consumptions',
            },
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', 'entitas_bisnis', 'remaining_qty'], name='idx_sm_item_eb_remaining'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', 'tanggal'], name='idx_sm_item_tanggal'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='idx_sm_source'),
        ),
        migrations.AddIndex(
            model_name='stockconsumption',
            index=models.Index(fields=['out_movement'], name='idx_sc_out'),
        ),
        migrations.AddIndex(
            model_name='stockconsumption',
            index=models.Index(fields=['in_movement'], name='idx_sc_in'),
        ),
    ]
