# Generated by Django 6.0.6 on 2026-07-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('entitas_bisnis', '0003_add_standar_akuntansi'),
        ('inventory', '0005_stockmovement_stockconsumption_and_more'),
        ('purchase', '0008_backfill_item_uom'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', 'entitas_bisnis_lv2', 'remaining_qty'], name='idx_sm_item_lv2_remaining'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', 'entitas_bisnis_lv3', 'remaining_qty'], name='idx_sm_item_lv3_remaining'),
        ),
    ]
