# Generated by Django 6.0.6 on 2026-07-16 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0003_add_standar_akuntansi'),
        ('inventory', '0007_backfill_stock_movements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30, verbose_name='Kode Gudang')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Gudang')),
                ('alamat', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='entitas_bisnis.entitasbisnis', verbose_name='Bisnis (Entitas Bisnis Lv1)')),
            ],
            options={
                'verbose_name': 'Gudang',
                'verbose_name_plural': 'Gudang',
                'ordering': ['entitas_bisnis', 'kode'],
                'unique_together': {('entitas_bisnis', 'kode')},
            },
        ),
    ]
