# Generated by Django 6.0.6 on 2026-07-16 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('entitas_bisnis', '0003_add_standar_akuntansi'),
        ('inventory', '0008_warehouse'),
        ('purchase', '0008_backfill_item_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.warehouse', verbose_name='Gudang'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', 'warehouse', 'remaining_qty'], name='idx_sm_item_wh_remaining'),
        ),
    ]
