# Generated by Django 6.0.6 on 2026-07-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_stockmovement_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='kode',
            field=models.CharField(editable=False, max_length=30, verbose_name='Kode Gudang'),
        ),
    ]
