# Generated by Django 6.0.6 on 2026-07-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_warehouse_kode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase_in', 'Pembelian Masuk'), ('sale_out', 'Penjualan Keluar'), ('production_in', 'Produksi Masuk (FG)'), ('production_out', 'Produksi Keluar (RM)'), ('saldo_awal', 'Saldo Awal'), ('adjustment_in', 'Penyesuaian Masuk'), ('adjustment_out', 'Penyesuaian Keluar'), ('opname_in', 'Opname Surplus'), ('opname_out', 'Opname Minus'), ('transfer_in', 'Transfer Masuk'), ('transfer_out', 'Transfer Keluar'), ('return_customer', 'Retur Pelanggan (Masuk)'), ('return_supplier', 'Retur Supplier (Keluar)')], db_index=True, max_length=20, verbose_name='Jenis Pergerakan'),
        ),
    ]
