# Generated by Django 6.0.6 on 2026-07-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutasiinventorydetail',
            name='mutasi_inventory_header',
        ),
        migrations.RemoveIndex(
            model_name='mutasiinventoryheader',
            name='idx_mih_entitas',
        ),
        migrations.DeleteModel(
            name='MutasiInventoryDetail',
        ),
        migrations.DeleteModel(
            name='MutasiInventoryHeader',
        ),
    ]
