# Generated by Django 6.0.6 on 2026-07-17 16:41

import apps.inventory.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0003_add_standar_akuntansi'),
        ('inventory', '0012_remove_mutasiinventorydetail_mutasi_inventory_header_and_more'),
        ('jurnal', '0003_add_jurnal_terhapus_and_persentase'),
        ('master_data', '0002_akun_is_kas_setara'),
        ('purchase', '0010_purchaseitem_input_qty_purchaseitem_input_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(editable=False, max_length=30, unique=True)),
                ('tanggal', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Diposting')], default='draft', max_length=10)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('akun_selisih', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='master_data.akun', verbose_name='Akun Selisih Persediaan')),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='entitas_bisnis.entitasbisnis')),
                ('entitas_bisnis_lv2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments_lv2', to='entitas_bisnis.entitasbisnislv2')),
                ('entitas_bisnis_lv3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments_lv3', to='entitas_bisnis.entitasbisnislv3')),
                ('jurnal_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jurnal.jurnalheader')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'ordering': ['-tanggal', '-created_at'],
            },
            bases=(apps.inventory.models._NomorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StockAdjustmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, help_text='Bertanda: + naik, - turun', max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, help_text='Untuk kenaikan', max_digits=19)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockadjustment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='purchase.itemmasterpurchase')),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.stockmovement')),
            ],
        ),
    ]
