# Generated by Django 6.0.6 on 2026-07-17 17:46

import apps.inventory.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0003_add_standar_akuntansi'),
        ('inventory', '0013_stockadjustment_stockadjustmentitem'),
        ('jurnal', '0003_add_jurnal_terhapus_and_persentase'),
        ('master_data', '0002_akun_is_kas_setara'),
        ('purchase', '0010_purchaseitem_input_qty_purchaseitem_input_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOpname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(editable=False, max_length=30, unique=True)),
                ('tanggal', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Diposting')], default='draft', max_length=10)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('akun_selisih', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_opnames', to='master_data.akun')),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_opnames', to='entitas_bisnis.entitasbisnis')),
                ('entitas_bisnis_lv2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_opnames_lv2', to='entitas_bisnis.entitasbisnislv2')),
                ('entitas_bisnis_lv3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_opnames_lv3', to='entitas_bisnis.entitasbisnislv3')),
                ('jurnal_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jurnal.jurnalheader')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_opnames', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Opname',
                'ordering': ['-tanggal', '-created_at'],
            },
            bases=(apps.inventory.models._NomorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StockOpnameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_sistem', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('qty_fisik', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('selisih', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='purchase.itemmasterpurchase')),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.stockmovement')),
                ('opname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockopname')),
            ],
        ),
    ]
