# Generated by Django 6.0.6 on 2026-07-17 18:20

import apps.inventory.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0003_add_standar_akuntansi'),
        ('inventory', '0014_stockopname_stockopnameitem'),
        ('jurnal', '0003_add_jurnal_terhapus_and_persentase'),
        ('master_data', '0002_akun_is_kas_setara'),
        ('purchase', '0010_purchaseitem_input_qty_purchaseitem_input_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(editable=False, max_length=30, unique=True)),
                ('tanggal', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Diposting')], default='draft', max_length=10)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('akun_perantara', models.ForeignKey(blank=True, help_text='Wajib bila lintas entitas (EB lv1 berbeda).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='master_data.akun')),
                ('eb_asal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_asal', to='entitas_bisnis.entitasbisnis')),
                ('eb_asal_lv2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_asal_lv2', to='entitas_bisnis.entitasbisnislv2')),
                ('eb_asal_lv3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_asal_lv3', to='entitas_bisnis.entitasbisnislv3')),
                ('eb_tujuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_tujuan', to='entitas_bisnis.entitasbisnis')),
                ('eb_tujuan_lv2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_tujuan_lv2', to='entitas_bisnis.entitasbisnislv2')),
                ('eb_tujuan_lv3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_tujuan_lv3', to='entitas_bisnis.entitasbisnislv3')),
                ('jurnal_header_asal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jurnal.jurnalheader')),
                ('jurnal_header_tujuan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jurnal.jurnalheader')),
                ('warehouse_asal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.warehouse')),
                ('warehouse_tujuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Transfer',
                'ordering': ['-tanggal', '-created_at'],
            },
            bases=(apps.inventory.models._NomorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='purchase.itemmasterpurchase')),
                ('movement_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.stockmovement')),
                ('movement_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.stockmovement')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer')),
            ],
        ),
    ]
