# Generated by Django 6.0.6 on 2026-07-17 19:32

import apps.inventory.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0003_add_standar_akuntansi'),
        ('inventory', '0015_stocktransfer_stocktransferitem'),
        ('jurnal', '0003_add_jurnal_terhapus_and_persentase'),
        ('purchase', '0010_purchaseitem_input_qty_purchaseitem_input_uom'),
        ('sales', '0010_salesitem_input_qty_salesitem_input_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(editable=False, max_length=30, unique=True)),
                ('tanggal', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Diposting')], default='draft', max_length=10)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retur_customers', to='entitas_bisnis.entitasbisnis')),
                ('entitas_bisnis_lv2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retur_customers_lv2', to='entitas_bisnis.entitasbisnislv2')),
                ('entitas_bisnis_lv3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retur_customers_lv3', to='entitas_bisnis.entitasbisnislv3')),
                ('jurnal_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jurnal.jurnalheader')),
                ('sales_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retur_customers', to='sales.salesheader')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retur_customers', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Retur Pelanggan',
                'ordering': ['-tanggal', '-created_at'],
            },
            bases=(apps.inventory.models._NomorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReturCustomerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, help_text='Biaya HPP asli dari transaksi penjualan', max_digits=19)),
                ('harga_jual', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='purchase.itemmasterpurchase')),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.stockmovement')),
                ('retur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.returcustomer')),
                ('sales_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retur_items', to='sales.salesitem')),
            ],
        ),
    ]
