# Generated by Django 6.0.6 on 2026-07-18 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_retursupplier_retursupplieritem'),
        ('purchase', '0010_purchaseitem_input_qty_purchaseitem_input_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReorderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_stock', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('reorder_point', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('reorder_qty', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_settings', to='purchase.itemmasterpurchase')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_settings', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Pengaturan Reorder',
                'unique_together': {('item', 'warehouse')},
            },
        ),
    ]
