# Generated by Django 6.0.4 on 2026-04-23 13:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitas_bisnis', '0001_initial'),
        ('master_data', '0001_initial'),
        ('purchase', '0003_add_nilai_residu_to_item_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='BOM ID')),
                ('tanggal_dibuat', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal BOM Dibuat')),
                ('catatan', models.TextField(blank=True, default='', verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills_of_materials', to='entitas_bisnis.entitasbisnis', verbose_name='Entitas Bisnis')),
                ('finished_good', models.OneToOneField(limit_choices_to={'tipe_item__in': ['FG', 'FGB']}, on_delete=django.db.models.deletion.PROTECT, related_name='bom', to='purchase.itemmasterpurchase', verbose_name='Finished Good')),
            ],
            options={
                'verbose_name': 'Bill of Materials',
                'verbose_name_plural': 'Bill of Materials',
            },
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_required', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Qty per Unit FG')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='manufacturing.billofmaterials', verbose_name='BOM')),
                ('raw_material', models.ForeignKey(limit_choices_to={'tipe_item__in': ['RM', 'RMB']}, on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines', to='purchase.itemmasterpurchase', verbose_name='Raw Material')),
            ],
            options={
                'verbose_name': 'BOM Line',
                'verbose_name_plural': 'BOM Lines',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Production ID')),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Tanggal Produksi')),
                ('qty_produced', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Qty Diproduksi')),
                ('overhead_cost', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=19, verbose_name='Overhead Cost')),
                ('rm_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), editable=False, max_digits=19, verbose_name='RM Cost')),
                ('total_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), editable=False, max_digits=19, verbose_name='Total Cost')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), editable=False, max_digits=19, verbose_name='Unit Cost FG')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Dibatalkan')], default='in_progress', max_length=20, verbose_name='Status')),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Lead Time (Hari)')),
                ('ordering_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='Ordering Cost')),
                ('holding_cost_pct', models.DecimalField(blank=True, decimal_places=4, help_text='Contoh: 0.1 = 10%', max_digits=5, null=True, verbose_name='Holding Cost %')),
                ('moq', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='MOQ')),
                ('target_turnover', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Target Turnover')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Catatan')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Sudah Diproses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='manufacturing.billofmaterials', verbose_name='BOM (Finished Good)')),
                ('coa_overhead', models.ForeignKey(blank=True, help_text='Wajib diisi jika ada Overhead Cost.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders_overhead', to='master_data.akun', verbose_name='Akun Overhead')),
                ('coa_produksi', models.ForeignKey(help_text='Akun WIP yang menampung biaya produksi sementara.', on_delete=django.db.models.deletion.PROTECT, related_name='production_orders_wip', to='master_data.akun', verbose_name='Akun Biaya Produksi (WIP)')),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='entitas_bisnis.entitasbisnis', verbose_name='Entitas Bisnis')),
            ],
            options={
                'verbose_name': 'Production Order',
                'verbose_name_plural': 'Production Orders',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRMConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_consumed', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Qty Dikonsumsi')),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Harga Satuan FIFO')),
                ('total_cost', models.DecimalField(decimal_places=4, editable=False, max_digits=19, verbose_name='Total Biaya')),
                ('bom_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumption_records', to='manufacturing.bomline', verbose_name='BOM Line')),
                ('fifo_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_consumptions', to='purchase.fifobatch', verbose_name='FIFO Batch')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rm_consumptions', to='manufacturing.productionorder', verbose_name='Production Order')),
            ],
            options={
                'verbose_name': 'Production RM Consumption',
                'verbose_name_plural': 'Production RM Consumptions',
            },
        ),
        migrations.AddIndex(
            model_name='billofmaterials',
            index=models.Index(fields=['entitas_bisnis', 'tanggal_dibuat'], name='idx_bom_eb_tanggal'),
        ),
        migrations.AddIndex(
            model_name='bomline',
            index=models.Index(fields=['bom', 'raw_material'], name='idx_bomline_bom_rm'),
        ),
        migrations.AlterUniqueTogether(
            name='bomline',
            unique_together={('bom', 'raw_material')},
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['entitas_bisnis', 'tanggal'], name='idx_po_eb_tanggal'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['bom', 'tanggal'], name='idx_po_bom_tanggal'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['status'], name='idx_po_status'),
        ),
        migrations.AddIndex(
            model_name='productionrmconsumption',
            index=models.Index(fields=['production_order', 'bom_line'], name='idx_prmc_po_bom'),
        ),
    ]
