# Generated by Django 6.0.4 on 2026-04-23 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_fix_metode_alokasi_max_length'),
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='fg_inventory_record',
            field=models.OneToOneField(blank=True, help_text='InventoryRecord yang dibuat saat produksi diproses.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_order', to='inventory.inventoryrecord', verbose_name='Inventory Record FG'),
        ),
    ]
