# Generated by Django 6.0.4 on 2026-04-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_add_fg_inventory_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='lama_pengerjaan',
            field=models.PositiveIntegerField(blank=True, help_text='Opsional (WIP): estimasi jumlah hari penyelesaian sejak tanggal produksi.', null=True, verbose_name='Lama Pengerjaan Estimasi (Hari)'),
        ),
    ]
