# Generated by Django 6.0.4 on 2026-04-24 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_add_lama_pengerjaan'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionorder',
            old_name='coa_overhead',
            new_name='coa_overhead_applied',
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='coa_overhead_applied',
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    'Akun liability/contra (2.x.x) yang menampung overhead diserap ke WIP. '
                    'JANGAN pilih akun beban (5.x.x). '
                    'Wajib diisi jika ada Overhead Cost.'
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='production_orders_overhead_applied',
                to='master_data.akun',
                verbose_name='Akun Manufacturing Overhead Applied',
            ),
        ),
    ]
