# Generated by Django 6.0.4 on 2026-04-24 13:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_rename_coa_overhead_to_applied'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='coa_overhead_applied',
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='overhead_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), editable=False, max_digits=19, verbose_name='Overhead Cost'),
        ),
        migrations.CreateModel(
            name='OverheadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Kategori')),
                ('overhead_type', models.CharField(choices=[('PRODUCTION', 'Production Overhead'), ('PERIOD', 'Period Overhead')], max_length=10, verbose_name='Sifat Overhead')),
                ('cost_driver', models.CharField(blank=True, choices=[('PER_UNIT', 'Per Unit Produksi'), ('PER_JAM_MESIN', 'Per Jam Mesin'), ('PER_JAM_TK', 'Per Jam Tenaga Kerja'), ('PERSEN_RM_COST', 'Persentase dari Biaya RM')], help_text='Dasar kalkulasi alokasi overhead ke produk. Wajib untuk Production Overhead.', max_length=20, null=True, verbose_name='Cost Driver')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coa_expense', models.ForeignKey(help_text='Akun beban (5.x.x) tempat biaya aktual dicatat.', on_delete=django.db.models.deletion.PROTECT, related_name='overhead_expense_categories', to='master_data.akun', verbose_name='Akun Beban Aktual')),
                ('coa_overhead_applied', models.ForeignKey(blank=True, help_text='Akun liability/contra yang di-kredit saat overhead diserap ke WIP. Wajib untuk Production Overhead. JANGAN pilih akun beban (5.x.x).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overhead_applied_categories', to='master_data.akun', verbose_name='Akun Overhead Applied (2.x.x)')),
            ],
            options={
                'verbose_name': 'Overhead Category',
                'verbose_name_plural': 'Overhead Categories',
                'ordering': ['overhead_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OverheadApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_bulan', models.CharField(max_length=7, verbose_name='Periode')),
                ('driver_value', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Nilai Driver')),
                ('rate_per_driver', models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Rate (Snapshot)')),
                ('amount_applied', models.DecimalField(decimal_places=4, editable=False, max_digits=19, verbose_name='Jumlah Overhead Applied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overhead_applied', to='manufacturing.productionorder', verbose_name='Production Order')),
                ('overhead_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_records', to='manufacturing.overheadcategory', verbose_name='Kategori Overhead')),
            ],
            options={
                'verbose_name': 'Overhead Applied',
                'verbose_name_plural': 'Overhead Applied',
                'indexes': [models.Index(fields=['production_order'], name='idx_oha_po'), models.Index(fields=['overhead_category', 'periode_bulan'], name='idx_oha_cat_period')],
                'unique_together': {('production_order', 'overhead_category')},
            },
        ),
        migrations.CreateModel(
            name='OverheadRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_bulan', models.CharField(help_text='Format: YYYY-MM, misal 2026-04', max_length=7, verbose_name='Periode (YYYY-MM)')),
                ('estimasi_total', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Estimasi Total Biaya (Rp)')),
                ('estimasi_volume', models.DecimalField(blank=True, decimal_places=4, help_text='Jumlah unit/jam yang diestimasi. Kosongkan untuk PERSEN_RM_COST.', max_digits=19, null=True, verbose_name='Estimasi Volume Driver')),
                ('rate_per_driver', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Auto-kalkulasi: estimasi_total / estimasi_volume. Untuk PERSEN_RM_COST: isi langsung sebagai desimal (0.10 = 10%).', max_digits=19, verbose_name='Rate per Driver')),
                ('aktual_total', models.DecimalField(blank=True, decimal_places=4, help_text='Isi di akhir periode untuk period-end closing.', max_digits=19, null=True, verbose_name='Aktual Total Biaya (Rp)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overhead_category', models.ForeignKey(limit_choices_to={'overhead_type': 'PRODUCTION'}, on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='manufacturing.overheadcategory', verbose_name='Kategori Overhead')),
            ],
            options={
                'verbose_name': 'Overhead Rate',
                'verbose_name_plural': 'Overhead Rates',
                'ordering': ['-periode_bulan', 'overhead_category__name'],
                'unique_together': {('overhead_category', 'periode_bulan')},
            },
        ),
    ]
