# Generated by Django 6.0.4 on 2026-04-27 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0005_overhead_system'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_bulan', models.CharField(help_text='Periode yang sudah ditutup. Format: YYYY-MM.', max_length=7, unique=True, verbose_name='Periode (YYYY-MM)')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Ditutup')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturing_period_closings', to=settings.AUTH_USER_MODEL, verbose_name='Ditutup Oleh')),
                ('coa_cogs', models.ForeignKey(blank=True, help_text='Akun COGS yang digunakan pada closing periode.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_period_closings', to='master_data.akun', verbose_name='Akun COGS')),
            ],
            options={
                'verbose_name': 'Period Closing',
                'verbose_name_plural': 'Period Closings',
                'ordering': ['-closed_at'],
                'indexes': [models.Index(fields=['periode_bulan'], name='idx_pc_periode')],
            },
        ),
    ]
