# Generated by Django 6.0.6 on 2026-07-15 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0003_add_standar_akuntansi'),
        ('manufacturing', '0006_periodclosing'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='entitas_bisnis_lv2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders_lv2', to='entitas_bisnis.entitasbisnislv2', verbose_name='Entitas Bisnis Lv2'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='entitas_bisnis_lv3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders_lv3', to='entitas_bisnis.entitasbisnislv3', verbose_name='Entitas Bisnis Lv3'),
        ),
    ]
