# Generated by Django 6.0.6 on 2026-07-16 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_stockmovement_warehouse_and_more'),
        ('manufacturing', '0007_productionorder_entitas_bisnis_lv2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='warehouse_fg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders_fg', to='inventory.warehouse', verbose_name='Gudang Hasil Produksi'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='warehouse_rm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders_rm', to='inventory.warehouse', verbose_name='Gudang Bahan Baku'),
        ),
    ]
