# Generated by Django 6.0.6 on 2026-07-16 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0008_productionorder_warehouse_fg_and_more'),
        ('uom', '0004_alter_itemuom_qty_in_stock_uom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomline',
            name='input_qty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Qty Input per Unit FG'),
        ),
        migrations.AddField(
            model_name='bomline',
            name='input_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines_input', to='uom.unitofmeasure', verbose_name='Satuan Input RM'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='input_qty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Qty Input (satuan asli)'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='input_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders_input', to='uom.unitofmeasure', verbose_name='Satuan Input FG'),
        ),
    ]
