# Generated by Django 6.0.4 on 2026-04-16 18:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitas_bisnis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalDisetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemilik', models.CharField(max_length=255, verbose_name='Nama Pemilik')),
                ('jumlah_modal', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Jumlah Modal Disetor')),
                ('persentase_kepemilikan', models.DecimalField(decimal_places=4, help_text='Contoh: 25.0000 = 25%', max_digits=7, verbose_name='Persentase Kepemilikan (%)')),
                ('tanggal_setor', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Tanggal Setor')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modal_disetors', to='entitas_bisnis.entitasbisnis', verbose_name='Entitas Bisnis')),
            ],
            options={
                'verbose_name': 'Modal Disetor',
                'verbose_name_plural': 'Modal Disetor',
                'ordering': ['-tanggal_setor', '-created_at'],
                'indexes': [models.Index(fields=['entitas_bisnis', 'tanggal_setor'], name='idx_md_eb_tanggal')],
            },
        ),
    ]
