# Generated by Django 6.0.4 on 2026-04-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekuitas', '0002_pemilik_modal_disetor_redesign'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modaldisetordebit',
            options={'verbose_name': 'Debit Modal Disetor', 'verbose_name_plural': 'Debit Modal Disetor'},
        ),
        migrations.AddField(
            model_name='modaldisetor',
            name='persentase_kepemilikan',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Opsional. Jika kosong, dihitung otomatis dari total modal entitas.', max_digits=8, null=True, verbose_name='Persentase Kepemilikan (%)'),
        ),
        migrations.AlterField(
            model_name='modaldisetordebit',
            name='akun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master_data.akun', verbose_name='Akun'),
        ),
        migrations.AlterField(
            model_name='modaldisetordebit',
            name='jumlah',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Jumlah'),
        ),
    ]
