# Generated by Django 6.0.7 on 2026-07-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama')),
                ('dimension', models.CharField(choices=[('count', 'Count / Jumlah'), ('weight', 'Berat'), ('volume', 'Volume'), ('length', 'Panjang'), ('area', 'Luas')], db_index=True, max_length=10, verbose_name='Dimensi')),
                ('factor_to_base', models.DecimalField(blank=True, decimal_places=8, help_text='Faktor universal ke satuan dasar dimensi. Kosongkan untuk satuan kemasan yang berbeda tiap produk (carton, box, dus, dll).', max_digits=24, null=True, verbose_name='Faktor ke Base')),
                ('is_base', models.BooleanField(default=False, verbose_name='Satuan Dasar')),
                ('is_system', models.BooleanField(default=False, verbose_name='Bawaan Sistem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Units of Measure',
                'ordering': ['dimension', 'kode'],
            },
        ),
    ]
