# Generated by Django 6.0.7 on 2026-07-15 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_add_pendapatan_module_choice'),
        ('uom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_in_stock_uom', models.DecimalField(decimal_places=8, help_text='Berapa banyak satuan stok dalam 1 satuan ini. Contoh: 1 carton = 24 pcs → 24.', max_digits=24, verbose_name='Jumlah dalam Stock UOM')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_uoms', to='purchase.itemmasterpurchase', verbose_name='Item')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_uoms', to='uom.unitofmeasure', verbose_name='Satuan')),
            ],
            options={
                'verbose_name': 'Item UOM',
                'verbose_name_plural': 'Item UOMs',
                'indexes': [models.Index(fields=['item', 'uom'], name='idx_itemuom_item_uom')],
                'unique_together': {('item', 'uom')},
            },
        ),
    ]
