# Generated by Django 6.0.7 on 2026-07-15 04:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0003_seed_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemuom',
            name='qty_in_stock_uom',
            field=models.DecimalField(decimal_places=8, help_text='Berapa banyak satuan stok dalam 1 satuan ini. Contoh: 1 carton = 24 pcs → 24.', max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))], verbose_name='Jumlah dalam Stock UOM'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='factor_to_base',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Faktor universal ke satuan dasar dimensi. Kosongkan untuk satuan kemasan yang berbeda tiap produk (carton, box, dus, dll).', max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))], verbose_name='Faktor ke Base'),
        ),
    ]
