# Generated by Django 6.0.4 on 2026-04-15 18:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitas_bisnis', '0001_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('tipe_item', models.CharField(choices=[('RM', 'Raw Material'), ('FG', 'Finished Good'), ('ITM', 'Item Lainnya'), ('ATP', 'Aset Tetap'), ('ALL', 'Aset Lainnya')], default='RM', max_length=10, verbose_name='Tipe Item')),
                ('entitas_bisnis', models.ManyToManyField(blank=True, related_name='kategori_items', to='entitas_bisnis.entitasbisnis', verbose_name='Entitas Bisnis')),
            ],
            options={
                'verbose_name': 'Kategori Item',
                'verbose_name_plural': 'Kategori Item',
                'unique_together': {('nama', 'tipe_item')},
            },
        ),
        migrations.CreateModel(
            name='ItemMasterPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255, unique=True)),
                ('tipe_item', models.CharField(choices=[('RM', 'Raw Material'), ('FG', 'Finished Good'), ('ITM', 'Item Lainnya'), ('ATP', 'Aset Tetap'), ('ALL', 'Aset Lainnya')], default='RM', max_length=10)),
                ('velocity_category', models.CharField(blank=True, choices=[('fast', 'Fast Moving'), ('medium', 'Medium (B)'), ('slow', 'Slow (C)'), ('dead', 'Dead Stock')], default='', max_length=20, verbose_name='Velocity Category')),
                ('lama_kadaluarsa', models.PositiveIntegerField(blank=True, help_text='Default jumlah hari sampai kadaluarsa dari tanggal pembelian.', null=True, verbose_name='Lama Kadaluarsa (Hari)')),
                ('threshold_days_outstanding', models.PositiveIntegerField(blank=True, help_text='Batas hari sebelum item dianggap stok mati.', null=True, verbose_name='Threshold Days Inv Outstanding')),
                ('masa_manfaat', models.PositiveIntegerField(blank=True, help_text='Masa manfaat aset dalam tahun.', null=True, verbose_name='Masa Manfaat (Tahun)')),
                ('metode_penyusutan', models.CharField(blank=True, choices=[('straight_line', 'Garis Lurus (Straight Line Method)'), ('double_declining', 'Saldo Menurun (Double Declining Balance Method)'), ('sum_of_years', 'Jumlah Angka Tahun (Sum of The Year Digit Method)'), ('service_hours', 'Satuan Jam Kerja (Service Hours Method)'), ('units_of_production', 'Satuan Hasil Produksi (Productive Output Method)')], default='', help_text='Metode penyusutan untuk Aset Tetap.', max_length=30, verbose_name='Metode Penyusutan')),
                ('metode_amortisasi', models.CharField(blank=True, choices=[('straight_line', 'Garis Lurus (Straight Line)'), ('declining_balance', 'Saldo Menurun (Declining Balance)'), ('units_of_production', 'Unit Produksi (Units of Production)'), ('revenue_based', 'Berbasis Pendapatan (Revenue Based)')], default='', help_text='Metode amortisasi untuk Aset Lainnya.', max_length=30, verbose_name='Metode Amortisasi')),
                ('metode_biaya_persediaan', models.CharField(blank=True, choices=[('fifo', 'FIFO (First In First Out)'), ('lifo', 'LIFO (Last In First Out)'), ('average', 'Average (Rata-rata Tertimbang)'), ('weighted_moving_average', 'Weighted Moving Average')], default='', help_text='Metode penentuan biaya persediaan untuk item inventori.', max_length=30, verbose_name='Metode Biaya Persediaan')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Harga Satuan Default')),
                ('coa_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_masters', to='master_data.akun', verbose_name='CoA Account')),
                ('entitas_bisnis', models.ManyToManyField(blank=True, related_name='item_masters', to='entitas_bisnis.entitasbisnis', verbose_name='Entitas Bisnis')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='purchase.kategoriitem')),
            ],
            options={
                'verbose_name': 'Item Master',
                'verbose_name_plural': 'Item Master',
            },
        ),
        migrations.CreateModel(
            name='PurchaseHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Tanggal')),
                ('deskripsi', models.TextField(blank=True, default='', verbose_name='Deskripsi')),
                ('is_locked', models.BooleanField(default=False, help_text='True jika periode sudah tutup buku.', verbose_name='Locked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Purchase Header',
                'verbose_name_plural': 'Purchase Headers',
                'ordering': ['-tanggal', '-created_at'],
                'indexes': [models.Index(fields=['tanggal', 'is_locked'], name='idx_ph_tanggal_locked')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseEntitasBisnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_groups', to='entitas_bisnis.entitasbisnis', verbose_name='Entitas Bisnis (Lv1)')),
                ('entitas_bisnis_lv2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_groups', to='entitas_bisnis.entitasbisnislv2', verbose_name='Entitas Bisnis Lv2')),
                ('entitas_bisnis_lv3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_groups', to='entitas_bisnis.entitasbisnislv3', verbose_name='Entitas Bisnis Lv3')),
                ('purchase_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitas_groups', to='purchase.purchaseheader')),
            ],
            options={
                'verbose_name': 'Purchase Entitas Bisnis',
                'verbose_name_plural': 'Purchase Entitas Bisnis',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Harga Satuan')),
                ('total_value', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=19, verbose_name='Total Nilai')),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Lead Time (Days)')),
                ('ordering_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='Ordering Cost')),
                ('holding_cost_pct', models.DecimalField(blank=True, decimal_places=4, help_text='Contoh: 0.1 = 10%', max_digits=5, null=True, verbose_name='Holding Cost %')),
                ('moq', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='MOQ')),
                ('target_turnover', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Target Turnover')),
                ('metode_alokasi_biaya', models.CharField(blank=True, choices=[('fifo', 'FIFO (First In First Out)'), ('lifo', 'LIFO (Last In First Out)'), ('average', 'Average (Rata-rata Tertimbang)'), ('weighted_moving_average', 'Weighted Moving Average')], default='', max_length=30, verbose_name='Metode Alokasi Biaya')),
                ('coa_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_item_coa', to='master_data.akun', verbose_name='CoA Account')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='purchase.itemmasterpurchase')),
                ('offset_coa_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_item_offset', to='master_data.akun', verbose_name='Offset CoA Account')),
                ('purchase_eb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaseentitasbisnis')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
            },
        ),
        migrations.CreateModel(
            name='FIFOBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(db_index=True)),
                ('quantity_in', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Qty Masuk')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Harga Satuan')),
                ('remaining_qty', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Sisa Qty')),
                ('batch_value', models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Nilai Batch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fifo_batches', to='purchase.itemmasterpurchase')),
                ('purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifo_batches', to='purchase.purchaseitem')),
            ],
            options={
                'verbose_name': 'FIFO Batch',
                'verbose_name_plural': 'FIFO Batches',
                'ordering': ['tanggal', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubTransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Sub-Transaction Type')),
                ('module', models.CharField(choices=[('purchase', 'Purchase'), ('sales', 'Sales')], db_index=True, default='purchase', max_length=20, verbose_name='Module')),
                ('direction', models.CharField(choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')], default='inflow', max_length=10, verbose_name='Transaction Type (Direction)')),
                ('default_offset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_transaction_types', to='master_data.akun', verbose_name='Default Offset Account')),
            ],
            options={
                'verbose_name': 'Sub-Transaction Type',
                'verbose_name_plural': 'Sub-Transaction Types',
            },
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='sub_transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='purchase.subtransactiontype', verbose_name='Sub-Transaction Type'),
        ),
        migrations.AddIndex(
            model_name='itemmasterpurchase',
            index=models.Index(fields=['tipe_item', 'nama'], name='idx_imp_tipe_nama'),
        ),
        migrations.AddIndex(
            model_name='itemmasterpurchase',
            index=models.Index(fields=['kategori'], name='idx_imp_kategori'),
        ),
        migrations.AddIndex(
            model_name='purchaseentitasbisnis',
            index=models.Index(fields=['purchase_header', 'entitas_bisnis'], name='idx_peb_header_eb'),
        ),
        migrations.AddIndex(
            model_name='purchaseentitasbisnis',
            index=models.Index(fields=['entitas_bisnis_lv2'], name='idx_peb_lv2'),
        ),
        migrations.AddIndex(
            model_name='purchaseentitasbisnis',
            index=models.Index(fields=['entitas_bisnis_lv3'], name='idx_peb_lv3'),
        ),
        migrations.AddIndex(
            model_name='fifobatch',
            index=models.Index(fields=['item', 'tanggal'], name='idx_fb_item_tanggal'),
        ),
        migrations.AddIndex(
            model_name='fifobatch',
            index=models.Index(fields=['item', 'remaining_qty'], name='idx_fb_item_remaining'),
        ),
        migrations.AlterUniqueTogether(
            name='subtransactiontype',
            unique_together={('nama', 'module')},
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['purchase_eb', 'item'], name='idx_pi_eb_item'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['item', 'sub_transaction_type'], name='idx_pi_item_stt'),
        ),
    ]
