# Generated by Django 6.0.4 on 2026-04-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0004_entitasbisnislv2_entitasbisnislv3_and_more'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmasterpurchase',
            name='entitas_bisnis',
            field=models.ManyToManyField(blank=True, related_name='item_masters', to='entitas_bisnis.entitasbisnis', verbose_name='Entitas Bisnis'),
        ),
        migrations.AddField(
            model_name='kategoriitem',
            name='entitas_bisnis',
            field=models.ManyToManyField(blank=True, related_name='kategori_items', to='entitas_bisnis.entitasbisnis', verbose_name='Entitas Bisnis'),
        ),
    ]
