# Generated by Django 6.0.4 on 2026-04-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmasterpurchase',
            name='tipe_item',
            field=models.CharField(choices=[('RM', 'Raw Material'), ('FG', 'Finished Good'), ('ITM', 'Item Lainnya'), ('RMB', 'Raw Material (Bulk)'), ('FGB', 'Finished Good (Bulk)'), ('ITMB', 'Item Lainnya (Bulk)'), ('ATP', 'Aset Tetap'), ('ALL', 'Aset Lainnya')], default='RM', max_length=10),
        ),
        migrations.AlterField(
            model_name='kategoriitem',
            name='tipe_item',
            field=models.CharField(choices=[('RM', 'Raw Material'), ('FG', 'Finished Good'), ('ITM', 'Item Lainnya'), ('RMB', 'Raw Material (Bulk)'), ('FGB', 'Finished Good (Bulk)'), ('ITMB', 'Item Lainnya (Bulk)'), ('ATP', 'Aset Tetap'), ('ALL', 'Aset Lainnya')], default='RM', max_length=10, verbose_name='Tipe Item'),
        ),
    ]
