# Generated by Django 6.0.4 on 2026-04-14 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0004_entitasbisnislv2_entitasbisnislv3_and_more'),
        ('purchase', '0002_itemmasterpurchase_entitas_bisnis_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseentitasbisnis',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='purchaseentitasbisnis',
            name='entitas_bisnis_lv2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_groups', to='entitas_bisnis.entitasbisnislv2', verbose_name='Entitas Bisnis Lv2'),
        ),
        migrations.AddField(
            model_name='purchaseentitasbisnis',
            name='entitas_bisnis_lv3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_groups', to='entitas_bisnis.entitasbisnislv3', verbose_name='Entitas Bisnis Lv3'),
        ),
        migrations.AlterField(
            model_name='purchaseentitasbisnis',
            name='entitas_bisnis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_groups', to='entitas_bisnis.entitasbisnis', verbose_name='Entitas Bisnis (Lv1)'),
        ),
        migrations.AddIndex(
            model_name='purchaseentitasbisnis',
            index=models.Index(fields=['entitas_bisnis_lv2'], name='idx_peb_lv2'),
        ),
        migrations.AddIndex(
            model_name='purchaseentitasbisnis',
            index=models.Index(fields=['entitas_bisnis_lv3'], name='idx_peb_lv3'),
        ),
    ]
