# Generated by Django 6.0.4 on 2026-04-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_itemmasterpurchase_tipe_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmasterpurchase',
            name='nilai_residu',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Nilai sisa aset di akhir masa manfaat (untuk ATP/ALL).', max_digits=19, verbose_name='Nilai Residu'),
        ),
    ]
