# Generated by Django 6.0.4 on 2026-05-12 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('purchase', '0003_add_nilai_residu_to_item_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtransactiontype',
            name='default_inventory_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stt_inventory', to='master_data.akun', verbose_name='Default Inventory Account'),
        ),
        migrations.AddField(
            model_name='subtransactiontype',
            name='default_payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stt_payment', to='master_data.akun', verbose_name='Default Payment Account'),
        ),
        migrations.AddField(
            model_name='subtransactiontype',
            name='default_revenue_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stt_revenue', to='master_data.akun', verbose_name='Default Revenue Account'),
        ),
        migrations.AddField(
            model_name='subtransactiontype',
            name='default_tax_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stt_tax', to='master_data.akun', verbose_name='Default Tax Account'),
        ),
        migrations.AddField(
            model_name='subtransactiontype',
            name='default_tax_type',
            field=models.CharField(blank=True, choices=[('ppn_keluaran', 'PPN Keluaran'), ('pph_23', 'PPh 23'), ('pph_21', 'PPh 21'), ('pph_4_2', 'PPh 4(2)')], default='', max_length=30, verbose_name='Default Tax Type'),
        ),
    ]
