# Generated by Django 6.0.4 on 2026-04-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_purchaseentitasbisnis_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmasterpurchase',
            name='tipe_item',
            field=models.CharField(choices=[('RM', 'Raw Material'), ('FG', 'Finished Good'), ('ITM', 'Item Lainnya'), ('ATP', 'Aset Tetap'), ('ALL', 'Aset Lainnya')], default='RM', max_length=10),
        ),
    ]
