# Generated by Django 6.0.4 on 2026-04-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_add_aset_tetap_aset_lainnya_item_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmasterpurchase',
            name='masa_manfaat',
            field=models.PositiveIntegerField(blank=True, help_text='Masa manfaat aset dalam tahun.', null=True, verbose_name='Masa Manfaat (Tahun)'),
        ),
        migrations.AddField(
            model_name='itemmasterpurchase',
            name='metode_amortisasi',
            field=models.CharField(blank=True, choices=[('straight_line', 'Garis Lurus (Straight Line)'), ('declining_balance', 'Saldo Menurun (Declining Balance)'), ('units_of_production', 'Unit Produksi (Units of Production)'), ('revenue_based', 'Berbasis Pendapatan (Revenue Based)')], default='', help_text='Metode amortisasi untuk Aset Lainnya.', max_length=30, verbose_name='Metode Amortisasi'),
        ),
        migrations.AddField(
            model_name='itemmasterpurchase',
            name='metode_penyusutan',
            field=models.CharField(blank=True, choices=[('straight_line', 'Garis Lurus (Straight Line)'), ('declining_balance', 'Saldo Menurun (Declining Balance)'), ('double_declining', 'Saldo Menurun Ganda (Double Declining Balance)'), ('sum_of_years', 'Jumlah Angka Tahun (Sum of Years Digits)'), ('units_of_production', 'Unit Produksi (Units of Production)')], default='', help_text='Metode penyusutan untuk Aset Tetap.', max_length=30, verbose_name='Metode Penyusutan'),
        ),
        migrations.AddField(
            model_name='kategoriitem',
            name='tipe_item',
            field=models.CharField(choices=[('RM', 'Raw Material'), ('FG', 'Finished Good'), ('ITM', 'Item Lainnya'), ('ATP', 'Aset Tetap'), ('ALL', 'Aset Lainnya')], default='RM', max_length=10, verbose_name='Tipe Item'),
        ),
        migrations.AlterField(
            model_name='kategoriitem',
            name='nama',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='kategoriitem',
            unique_together={('nama', 'tipe_item')},
        ),
    ]
