# Generated by Django 6.0.4 on 2026-04-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_itemmasterpurchase_masa_manfaat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmasterpurchase',
            name='metode_biaya_persediaan',
            field=models.CharField(blank=True, choices=[('fifo', 'FIFO (First In First Out)'), ('lifo', 'LIFO (Last In First Out)'), ('average', 'Average (Rata-rata Tertimbang)'), ('weighted_moving_average', 'Weighted Moving Average')], default='', help_text='Metode penentuan biaya persediaan untuk item inventori.', max_length=30, verbose_name='Metode Biaya Persediaan'),
        ),
        migrations.AlterField(
            model_name='itemmasterpurchase',
            name='metode_penyusutan',
            field=models.CharField(blank=True, choices=[('straight_line', 'Garis Lurus (Straight Line Method)'), ('double_declining', 'Saldo Menurun (Double Declining Balance Method)'), ('sum_of_years', 'Jumlah Angka Tahun (Sum of The Year Digit Method)'), ('service_hours', 'Satuan Jam Kerja (Service Hours Method)'), ('units_of_production', 'Satuan Hasil Produksi (Productive Output Method)')], default='', help_text='Metode penyusutan untuk Aset Tetap.', max_length=30, verbose_name='Metode Penyusutan'),
        ),
    ]
