# Generated by Django 6.0.4 on 2026-06-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_subtransactiontype_payment_term_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtransactiontype',
            name='module',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sales', 'Sales'), ('pendapatan', 'Pendapatan')], db_index=True, default='purchase', max_length=20, verbose_name='Module'),
        ),
    ]
