# Generated by Django 6.0.4 on 2026-04-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_itemmasterpurchase_metode_biaya_persediaan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmasterpurchase',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='itemmasterpurchase',
            name='lama_kadaluarsa',
            field=models.PositiveIntegerField(blank=True, help_text='Default jumlah hari sampai kadaluarsa dari tanggal pembelian.', null=True, verbose_name='Lama Kadaluarsa (Hari)'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='metode_alokasi_biaya',
            field=models.CharField(blank=True, choices=[('fifo', 'FIFO (First In First Out)'), ('lifo', 'LIFO (Last In First Out)'), ('average', 'Average (Rata-rata Tertimbang)'), ('weighted_moving_average', 'Weighted Moving Average')], default='', max_length=30, verbose_name='Metode Alokasi Biaya'),
        ),
    ]
