# Generated by Django 6.0.7 on 2026-07-15 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_add_pendapatan_module_choice'),
        ('uom', '0002_itemuom'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmasterpurchase',
            name='purchase_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_purchase', to='uom.unitofmeasure', verbose_name='Satuan Pembelian'),
        ),
        migrations.AddField(
            model_name='itemmasterpurchase',
            name='sales_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_sales', to='uom.unitofmeasure', verbose_name='Satuan Penjualan'),
        ),
        migrations.AddField(
            model_name='itemmasterpurchase',
            name='stock_uom',
            field=models.ForeignKey(blank=True, help_text='Satuan penyimpanan/penilaian (kanonik item).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_stock', to='uom.unitofmeasure', verbose_name='Satuan Stok'),
        ),
    ]
