# Generated by Django 6.0.4 on 2026-04-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_remove_itemmasterpurchase_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtransactiontype',
            name='module',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sales', 'Sales')], db_index=True, default='purchase', max_length=20, verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='subtransactiontype',
            name='nama',
            field=models.CharField(max_length=255, verbose_name='Sub-Transaction Type'),
        ),
        migrations.AlterUniqueTogether(
            name='subtransactiontype',
            unique_together={('nama', 'module')},
        ),
    ]
