# Generated by Django 6.0.6 on 2026-07-16 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_purchaseitem_warehouse'),
        ('uom', '0004_alter_itemuom_qty_in_stock_uom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='input_qty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Qty Input (satuan asli)'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='input_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items_input', to='uom.unitofmeasure', verbose_name='Satuan Input'),
        ),
    ]
