# Generated by Django 6.0.6 on 2026-07-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_purchaseitem_input_qty_purchaseitem_input_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriitem',
            name='masa_manfaat_default',
            field=models.PositiveIntegerField(blank=True, help_text='Default umur ekonomis untuk aset kategori ini.', null=True, verbose_name='Masa Manfaat Default (Tahun)'),
        ),
        migrations.AddField(
            model_name='kategoriitem',
            name='metode_penyusutan_default',
            field=models.CharField(blank=True, default='', help_text='Default metode penyusutan untuk aset kategori ini.', max_length=30, verbose_name='Metode Penyusutan Default'),
        ),
    ]
