# Generated by Django 6.0.6 on 2026-07-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_kategoriitem_masa_manfaat_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategoriitem',
            name='metode_penyusutan_default',
            field=models.CharField(blank=True, choices=[('straight_line', 'Garis Lurus (Straight Line Method)'), ('double_declining', 'Saldo Menurun (Double Declining Balance Method)'), ('sum_of_years', 'Jumlah Angka Tahun (Sum of The Year Digit Method)'), ('service_hours', 'Satuan Jam Kerja (Service Hours Method)'), ('units_of_production', 'Satuan Hasil Produksi (Productive Output Method)')], default='', help_text='Default metode penyusutan untuk aset kategori ini.', max_length=30, verbose_name='Metode Penyusutan Default'),
        ),
    ]
