# Generated by Django 6.0.6 on 2026-07-22 20:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos_catalog', '0002_initial'),
        ('pos_config', '0001_initial'),
        ('purchase', '0010_purchaseitem_input_qty_purchaseitem_input_uom'),
        ('sales', '0010_salesitem_input_qty_salesitem_input_uom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatorCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregator', models.CharField(choices=[('GOFOOD', 'GoFood'), ('GRABFOOD', 'GrabFood'), ('SHOPEEFOOD', 'ShopeeFood')], max_length=20)),
                ('country', models.CharField(default='ID', max_length=2)),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('PRODUCTION', 'Production')], default='PRODUCTION', max_length=20)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret_encrypted', models.TextField(blank=True)),
                ('enterprise_id', models.CharField(blank=True, max_length=255)),
                ('access_token_encrypted', models.TextField(blank=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_encrypted', models.TextField(blank=True)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_secret_encrypted', models.TextField(blank=True)),
                ('pos_trigger', models.CharField(choices=[('ON_CREATED', 'Saat pesanan masuk'), ('ON_ACCEPTED', 'Saat pesanan diterima'), ('ON_DRIVER_ARRIVED', 'Saat driver tiba')], default='ON_CREATED', help_text='Kapan pesanan diteruskan ke dapur. Default: saat pesanan masuk.', max_length=20, verbose_name='Kirim ke dapur saat')),
                ('tax_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Kosongkan = ikut konfigurasi merchant.', max_digits=5, null=True, verbose_name='Tax % channel ini')),
                ('price_markup_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Menaikkan harga jual di channel ini untuk menutup komisi aggregator.', max_digits=5, verbose_name='Markup harga %')),
                ('auto_accept_orders', models.BooleanField(default=True, help_text='Terima pesanan otomatis. Matikan jika dapur ingin konfirmasi manual.')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregator_credentials', to='pos_config.merchantposconfig')),
            ],
            options={
                'verbose_name': 'Kredensial Aggregator',
                'verbose_name_plural': 'Kredensial Aggregator',
            },
        ),
        migrations.CreateModel(
            name='AggregatorItemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Kosongkan = harga katalog + markup channel.', max_digits=15, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('external_item_id', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregator_settings', to='pos_catalog.catalogitem')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_settings', to='pos_aggregator.aggregatorcredential')),
            ],
            options={
                'verbose_name': 'Harga Item per Channel',
                'verbose_name_plural': 'Harga Item per Channel',
            },
        ),
        migrations.CreateModel(
            name='AggregatorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregator', models.CharField(choices=[('GOFOOD', 'GoFood'), ('GRABFOOD', 'GrabFood'), ('SHOPEEFOOD', 'ShopeeFood')], db_index=True, max_length=20)),
                ('external_order_id', models.CharField(db_index=True, max_length=255)),
                ('short_order_number', models.CharField(blank=True, max_length=50)),
                ('status', models.IntegerField(choices=[(10, 'Pesanan Masuk'), (20, 'Diterima'), (30, 'Diproses'), (40, 'Siap Diambil'), (50, 'Driver Tiba'), (60, 'Diambil Driver'), (70, 'Selesai'), (90, 'Dibatalkan')], db_index=True, default=10)),
                ('external_status', models.CharField(blank=True, max_length=100)),
                ('order_type', models.CharField(choices=[('DELIVERY', 'Pesan Antar'), ('TAKEAWAY', 'Bawa Pulang'), ('DINE_IN', 'Makan di Tempat')], default='DELIVERY', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('merchant_funded_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Bagian diskon yang ditanggung merchant — hanya ini yang mengurangi pendapatan.', max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('packaging_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('delivery_address', models.TextField(blank=True)),
                ('driver_name', models.CharField(blank=True, max_length=200)),
                ('driver_phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('posting_error', models.TextField(blank=True)),
                ('released_to_kitchen', models.BooleanField(default=False)),
                ('has_unmapped_items', models.BooleanField(default=False, help_text='Aggregator mengirim item yang tidak cocok dengan katalog. Perlu ditinjau.')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_header', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aggregator_order', to='sales.salesheader')),
            ],
            options={
                'verbose_name': 'Pesanan Aggregator',
                'verbose_name_plural': 'Pesanan Aggregator',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AggregatorOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_item_id', models.CharField(blank=True, max_length=255)),
                ('name_snapshot', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('modifier_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aggregator_order_items', to='purchase.itemmasterpurchase')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos_aggregator.aggregatororder')),
            ],
            options={
                'verbose_name': 'Item Pesanan Aggregator',
                'verbose_name_plural': 'Item Pesanan Aggregator',
            },
        ),
        migrations.CreateModel(
            name='AggregatorOrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('detail', models.TextField(blank=True)),
                ('from_status', models.IntegerField(blank=True, choices=[(10, 'Pesanan Masuk'), (20, 'Diterima'), (30, 'Diproses'), (40, 'Siap Diambil'), (50, 'Driver Tiba'), (60, 'Diambil Driver'), (70, 'Selesai'), (90, 'Dibatalkan')], null=True)),
                ('to_status', models.IntegerField(blank=True, choices=[(10, 'Pesanan Masuk'), (20, 'Diterima'), (30, 'Diproses'), (40, 'Siap Diambil'), (50, 'Driver Tiba'), (60, 'Diambil Driver'), (70, 'Selesai'), (90, 'Dibatalkan')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aggregator_order_logs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pos_aggregator.aggregatororder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AggregatorOrderModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('name_snapshot', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='pos_aggregator.aggregatororderitem')),
            ],
        ),
        migrations.CreateModel(
            name='AggregatorStoreLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregator', models.CharField(choices=[('GOFOOD', 'GoFood'), ('GRABFOOD', 'GrabFood'), ('SHOPEEFOOD', 'ShopeeFood')], max_length=20)),
                ('external_store_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('external_store_name', models.CharField(blank=True, max_length=255)),
                ('external_store_address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NOT_LINKED', 'Belum Terhubung'), ('PENDING', 'Menunggu Aggregator'), ('LINKED', 'Terhubung'), ('FAILED', 'Gagal')], default='NOT_LINKED', max_length=20)),
                ('status_detail', models.TextField(blank=True)),
                ('activation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('menu_sync_status', models.CharField(choices=[('PENDING', 'Menunggu'), ('IN_PROGRESS', 'Berjalan'), ('SUCCESS', 'Berhasil'), ('FAILED', 'Gagal')], default='PENDING', max_length=20)),
                ('menu_synced_at', models.DateTimeField(blank=True, null=True)),
                ('menu_sync_detail', models.TextField(blank=True)),
                ('is_accepting_orders', models.BooleanField(default=False, help_text='Outlet menerima pesanan di aggregator. Dimatikan saat tutup.')),
                ('is_live', models.BooleanField(default=False, help_text='Sudah lulus pemeriksaan dan boleh menerima pesanan sungguhan.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_links', to='pos_aggregator.aggregatorcredential')),
                ('store_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregator_links', to='pos_config.storeposconfig')),
            ],
            options={
                'verbose_name': 'Hubungan Cabang–Aggregator',
                'verbose_name_plural': 'Hubungan Cabang–Aggregator',
            },
        ),
        migrations.AddField(
            model_name='aggregatororder',
            name='store_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='pos_aggregator.aggregatorstorelink'),
        ),
        migrations.CreateModel(
            name='OnboardingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('NOT_STARTED', 'Belum Dimulai'), ('PREREQ_CONFIRMED', 'Prasyarat Dikonfirmasi'), ('ACCOUNT_CONNECTED', 'Akun Terhubung'), ('WEBHOOKS_REGISTERED', 'Webhook Terdaftar'), ('STORES_LINKED', 'Cabang Terhubung'), ('MENU_SYNCED', 'Menu Tersinkron'), ('PREFLIGHT_PASSED', 'Pemeriksaan Lolos'), ('LIVE', 'Live'), ('DISCONNECTED', 'Terputus')], default='NOT_STARTED', max_length=30)),
                ('last_error', models.TextField(blank=True)),
                ('preflight_results', models.JSONField(blank=True, default=list)),
                ('oauth_state', models.CharField(blank=True, max_length=128)),
                ('oauth_state_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='pos_aggregator.aggregatorcredential')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aggregator_onboardings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesi Onboarding',
                'verbose_name_plural': 'Sesi Onboarding',
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregator', models.CharField(choices=[('GOFOOD', 'GoFood'), ('GRABFOOD', 'GrabFood'), ('SHOPEEFOOD', 'ShopeeFood')], db_index=True, max_length=20)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('external_event_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('external_order_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('external_store_id', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('signature_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('RECEIVED', 'Diterima'), ('PROCESSED', 'Diproses'), ('DUPLICATE', 'Duplikat'), ('FAILED', 'Gagal')], db_index=True, default='RECEIVED', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('attempts', models.IntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['status', 'received_at'], name='idx_webhook_status_time')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_event_id__gt', '')), fields=('aggregator', 'external_event_id'), name='uniq_webhook_event_id')],
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('external_subscription_id', models.CharField(blank=True, max_length=255)),
                ('callback_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu'), ('IN_PROGRESS', 'Berjalan'), ('SUCCESS', 'Berhasil'), ('FAILED', 'Gagal')], default='PENDING', max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to='pos_aggregator.aggregatorcredential')),
            ],
            options={
                'verbose_name': 'Langganan Webhook',
                'verbose_name_plural': 'Langganan Webhook',
            },
        ),
        migrations.AddIndex(
            model_name='aggregatorcredential',
            index=models.Index(fields=['aggregator', 'is_active'], name='idx_aggcred_type_active'),
        ),
        migrations.AlterUniqueTogether(
            name='aggregatorcredential',
            unique_together={('merchant_config', 'aggregator')},
        ),
        migrations.AlterUniqueTogether(
            name='aggregatoritemsetting',
            unique_together={('credential', 'catalog_item')},
        ),
        migrations.AddConstraint(
            model_name='aggregatorstorelink',
            constraint=models.UniqueConstraint(condition=models.Q(('external_store_id__gt', '')), fields=('aggregator', 'external_store_id'), name='uniq_aggregator_external_store'),
        ),
        migrations.AlterUniqueTogether(
            name='aggregatorstorelink',
            unique_together={('store_config', 'aggregator')},
        ),
        migrations.AddIndex(
            model_name='aggregatororder',
            index=models.Index(fields=['status', 'created_at'], name='idx_aggorder_status_time'),
        ),
        migrations.AddIndex(
            model_name='aggregatororder',
            index=models.Index(fields=['store_link', 'status'], name='idx_aggorder_store_status'),
        ),
        migrations.AddConstraint(
            model_name='aggregatororder',
            constraint=models.UniqueConstraint(fields=('aggregator', 'external_order_id'), name='uniq_aggregator_order'),
        ),
        migrations.AlterUniqueTogether(
            name='webhooksubscription',
            unique_together={('credential', 'event_name')},
        ),
    ]
