# Generated by Django 6.0.4 on 2026-06-02 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0002_is_company_profile'),
        ('jurnal', '0003_add_jurnal_terhapus_and_persentase'),
        ('master_data', '0001_initial'),
        ('purchase', '0005_subtransactiontype_payment_term_days'),
        ('utang', '0002_utang_jatuh_tempo_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UtangAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='utang/attachments/%Y/%m/', verbose_name='File')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nama File')),
                ('jenis_dokumen', models.CharField(choices=[('invoice', 'Invoice'), ('kontrak', 'Kontrak'), ('spk', 'SPK'), ('perjanjian', 'Perjanjian Kredit'), ('berita_acara', 'Berita Acara'), ('kuitansi', 'Kuitansi'), ('lainnya', 'Lainnya')], default='lainnya', max_length=30, verbose_name='Jenis Dokumen')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Diupload Pada')),
            ],
            options={
                'verbose_name': 'Dokumen Utang',
                'verbose_name_plural': 'Dokumen Utang',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UtangAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_utang', models.CharField(blank=True, default='', max_length=100, verbose_name='Nomor Utang')),
                ('action', models.CharField(choices=[('CREATE', 'Dibuat'), ('EDIT', 'Diedit'), ('SUBMIT_APPROVAL', 'Diajukan Persetujuan'), ('APPROVE', 'Disetujui'), ('REJECT', 'Ditolak'), ('POST', 'Diposting'), ('PAYMENT', 'Pembayaran'), ('REVERSE_PAYMENT', 'Batalkan Pembayaran'), ('REVERSE', 'Dibalik/Dihapus'), ('UNLOCK', 'Dibuka Kunci')], max_length=30, verbose_name='Aksi')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Waktu')),
                ('before_json', models.JSONField(blank=True, default=dict, verbose_name='Sebelum')),
                ('after_json', models.JSONField(blank=True, default=dict, verbose_name='Sesudah')),
                ('notes', models.CharField(blank=True, default='', max_length=512, verbose_name='Catatan')),
            ],
            options={
                'verbose_name': 'Audit Log Utang',
                'verbose_name_plural': 'Audit Log Utang',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='utangheader',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('', '-'), ('pending', 'Menunggu'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='', max_length=20, verbose_name='Status Persetujuan'),
        ),
        migrations.AddField(
            model_name='utangheader',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Disetujui Pada'),
        ),
        migrations.AddField(
            model_name='utangheader',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utang_approved', to=settings.AUTH_USER_MODEL, verbose_name='Disetujui Oleh'),
        ),
        migrations.AddField(
            model_name='utangheader',
            name='coa_source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utang_sources', to='master_data.akun', verbose_name='Akun Asal (Debet)'),
        ),
        migrations.AddField(
            model_name='utangheader',
            name='jenis_utang',
            field=models.CharField(choices=[('usaha', 'Utang Usaha'), ('bank', 'Pinjaman Bank'), ('leasing', 'Leasing'), ('pajak', 'Utang Pajak'), ('gaji', 'Utang Gaji'), ('pemegang_saham', 'Pinjaman Pemegang Saham'), ('antar_entitas', 'Utang Antar Entitas'), ('lainnya', 'Lainnya')], default='usaha', max_length=30, verbose_name='Jenis Utang'),
        ),
        migrations.AddField(
            model_name='utangheader',
            name='jurnal_pembentukan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utang_pembentukan', to='jurnal.jurnalheader', verbose_name='Jurnal Pembentukan'),
        ),
        migrations.AddField(
            model_name='utangheader',
            name='kategori_jangka_waktu',
            field=models.CharField(choices=[('short_term', 'Jangka Pendek'), ('long_term', 'Jangka Panjang')], default='short_term', max_length=20, verbose_name='Kategori Jangka Waktu'),
        ),
        migrations.AddField(
            model_name='utangheader',
            name='kreditor',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Kreditor'),
        ),
        migrations.AddField(
            model_name='utangheader',
            name='nomor_referensi',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nomor Referensi'),
        ),
        migrations.AddField(
            model_name='utangheader',
            name='requires_approval',
            field=models.BooleanField(default=False, verbose_name='Perlu Persetujuan'),
        ),
        migrations.AlterField(
            model_name='utangheader',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('waiting_approval', 'Menunggu Persetujuan'), ('open', 'Terbuka'), ('partial', 'Sebagian Dibayar'), ('paid', 'Lunas'), ('overdue', 'Jatuh Tempo'), ('cancelled', 'Dibatalkan'), ('written_off', 'Dihapusbukukan')], default='open', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='utangheader',
            index=models.Index(fields=['jenis_utang', 'status'], name='idx_utang_jenis_status'),
        ),
        migrations.AddField(
            model_name='utangattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utang_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Diupload Oleh'),
        ),
        migrations.AddField(
            model_name='utangattachment',
            name='utang_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='utang.utangheader', verbose_name='Utang Header'),
        ),
        migrations.AddField(
            model_name='utangauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utang_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='utangauditlog',
            name='utang_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='utang.utangheader', verbose_name='Utang Header'),
        ),
        migrations.AddIndex(
            model_name='utangauditlog',
            index=models.Index(fields=['nomor_utang', 'timestamp'], name='idx_ual_nomor_ts'),
        ),
    ]
