# Generated by Django 6.0.4 on 2026-06-02 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('utang', '0003_liability_v1'),
    ]

    operations = [
        migrations.AddField(
            model_name='utangheader',
            name='jenis_bunga',
            field=models.CharField(choices=[('tanpa_bunga', 'Tanpa Bunga'), ('flat', 'Flat'), ('anuitas', 'Anuitas (Efektif)')], default='tanpa_bunga', max_length=20, verbose_name='Jenis Bunga'),
        ),
        migrations.AddField(
            model_name='utangheader',
            name='jumlah_angsuran',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jumlah Angsuran'),
        ),
        migrations.AddField(
            model_name='utangheader',
            name='periode_angsuran',
            field=models.CharField(choices=[('bulanan', 'Bulanan'), ('triwulanan', 'Triwulanan (3 Bulan)'), ('semesteran', 'Semesteran (6 Bulan)'), ('tahunan', 'Tahunan')], default='bulanan', max_length=20, verbose_name='Periode Angsuran'),
        ),
        migrations.AddField(
            model_name='utangheader',
            name='suku_bunga',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Suku Bunga (% per tahun)'),
        ),
        migrations.AlterField(
            model_name='utangheader',
            name='coa_source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utang_sources', to='master_data.akun', verbose_name='Akun Debet'),
        ),
    ]
