# Generated by Django 6.0.4 on 2026-06-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0003_add_jurnal_terhapus_and_persentase'),
        ('utang', '0004_bunga_angsuran'),
    ]

    operations = [
        migrations.AddField(
            model_name='utangheader',
            name='jurnal_reklasifikasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utang_reklasifikasi', to='jurnal.jurnalheader', verbose_name='Jurnal Reklasifikasi'),
        ),
    ]
