# Generated by Django 6.0.4 on 2026-06-04 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0003_add_jurnal_terhapus_and_persentase'),
        ('utang', '0005_jurnal_reklasifikasi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utangheader',
            name='jurnal_reklasifikasi',
        ),
        migrations.CreateModel(
            name='UtangReklasifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Jumlah')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('catatan', models.CharField(blank=True, default='', max_length=255, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utang_reklasifikasi_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('jurnal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='utang_reklasifikasi_entry', to='jurnal.jurnalheader', verbose_name='Jurnal Reklasifikasi')),
                ('utang_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reklasifikasi_entries', to='utang.utangheader', verbose_name='Utang Header')),
            ],
            options={
                'verbose_name': 'Reklasifikasi Utang',
                'verbose_name_plural': 'Reklasifikasi Utang',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
    ]
