# Generated by Django 6.0.4 on 2026-06-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utang', '0006_multi_reklasifikasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='utangpembayaran',
            name='angsuran_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nomor Angsuran'),
        ),
    ]
