# Generated by Django 6.0.4 on 2026-05-06 18:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitas_bisnis', '0002_is_company_profile'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantPOSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pos_active', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pos/logos/')),
                ('qris_image', models.ImageField(blank=True, null=True, upload_to='pos/qris/')),
                ('default_tax_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('default_service_charge_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('tax_inclusive', models.BooleanField(default=False)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entitas_bisnis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos_config', to='entitas_bisnis.entitasbisnis')),
                ('revenue_account', models.ForeignKey(blank=True, help_text='Akun pendapatan default untuk penjualan POS', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_revenue_merchant', to='master_data.akun')),
            ],
            options={
                'verbose_name': 'Merchant POS Config',
            },
        ),
        migrations.CreateModel(
            name='StorePOSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('service_charge_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('printer_type', models.CharField(blank=True, choices=[('EPSON_TM', 'Epson TM Series'), ('STAR_TSP', 'Star TSP Series'), ('GENERIC_ESCPOS', 'Generic ESC/POS')], max_length=20)),
                ('printer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('printer_port', models.IntegerField(default=9100)),
                ('receipt_header', models.TextField(blank=True)),
                ('receipt_footer', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entitas_bisnis_lv2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos_config', to='entitas_bisnis.entitasbisnislv2')),
                ('merchant_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='pos_config.merchantposconfig')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('method_type', models.CharField(choices=[('CASH', 'Tunai'), ('QRIS', 'QRIS'), ('TRANSFER', 'Transfer Bank'), ('OTHER', 'Lainnya')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('merchant_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='pos_config.merchantposconfig')),
                ('offset_coa_account', models.ForeignKey(blank=True, help_text='Akun debit saat pembayaran diterima (Kas, Bank, dll)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_payment_method_offset', to='master_data.akun')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='pos_config.storeposconfig')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='pos_config.storeposconfig')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_logs', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_logs', to='pos_config.storeposconfig')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='pos_config.workshift')),
            ],
        ),
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500)),
                ('p256dh_key', models.CharField(max_length=200)),
                ('auth_key', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('CASHIER', 'Kasir'), ('KITCHEN', 'Dapur'), ('MANAGER', 'Manajer')], default='CASHIER', max_length=20)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='pos_config.storeposconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
