# Generated by Django 6.0.6 on 2026-07-22 20:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitas_bisnis', '0003_add_standar_akuntansi'),
        ('master_data', '0002_akun_is_kas_setara'),
        ('purchase', '0010_purchaseitem_input_qty_purchaseitem_input_uom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantPOSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pos_active', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pos/logos/')),
                ('qris_image', models.ImageField(blank=True, null=True, upload_to='pos/qris/')),
                ('default_tax_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('default_service_charge_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('tax_inclusive', models.BooleanField(default=False)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_payment_account', models.ForeignKey(blank=True, help_text='Akun kas/piutang default jika PaymentMethod tidak punya payment_account sendiri.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_merchant_payment', to='master_data.akun', verbose_name='Default Payment Account')),
                ('entitas_bisnis_lv2', models.OneToOneField(help_text='Perusahaan operasional pemegang akun merchant.', on_delete=django.db.models.deletion.CASCADE, related_name='pos_config', to='entitas_bisnis.entitasbisnislv2', verbose_name='Entitas Bisnis Level 2')),
                ('offset_coa_account', models.ForeignKey(blank=True, help_text='Akun HPP — digunakan sebagai offset_coa_account di SalesItem.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_merchant_offset', to='master_data.akun', verbose_name='HPP Account')),
                ('revenue_account', models.ForeignKey(blank=True, help_text='Akun pendapatan default untuk penjualan POS', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_revenue_merchant', to='master_data.akun')),
                ('sub_transaction_type', models.ForeignKey(blank=True, help_text='Sub-tipe transaksi penjualan POS (module=sales, direction=outflow).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_merchant_configs', to='purchase.subtransactiontype', verbose_name='Sub-Transaction Type')),
            ],
            options={
                'verbose_name': 'Merchant POS Config',
                'verbose_name_plural': 'Merchant POS Config',
            },
        ),
        migrations.CreateModel(
            name='StorePOSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Kosongkan = ikut merchant.', max_digits=5, null=True, verbose_name='Tax % (Override)')),
                ('service_charge_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Kosongkan = ikut merchant.', max_digits=5, null=True, verbose_name='Service Charge % (Override)')),
                ('qris_image', models.ImageField(blank=True, null=True, upload_to='pos/qris/')),
                ('printer_type', models.CharField(blank=True, choices=[('EPSON_TM', 'Epson TM Series'), ('STAR_TSP', 'Star TSP Series'), ('GENERIC_ESCPOS', 'Generic ESC/POS')], max_length=20)),
                ('printer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('printer_port', models.IntegerField(default=9100)),
                ('receipt_header', models.TextField(blank=True)),
                ('receipt_footer', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_store_payment', to='master_data.akun', verbose_name='Payment Account (Override)')),
                ('entitas_bisnis_lv3', models.OneToOneField(help_text='Cabang / outlet fisik.', on_delete=django.db.models.deletion.CASCADE, related_name='pos_config', to='entitas_bisnis.entitasbisnislv3', verbose_name='Entitas Bisnis Level 3')),
                ('merchant_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='pos_config.merchantposconfig')),
                ('offset_coa_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_store_offset', to='master_data.akun', verbose_name='HPP Account (Override)')),
                ('revenue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_store_revenue', to='master_data.akun', verbose_name='Revenue Account (Override)')),
                ('sub_transaction_type', models.ForeignKey(blank=True, help_text='Kosongkan = ikut merchant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_store_configs', to='purchase.subtransactiontype', verbose_name='Sub-Transaction Type (Override)')),
            ],
            options={
                'verbose_name': 'Store POS Config',
                'verbose_name_plural': 'Store POS Config',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('method_type', models.CharField(choices=[('CASH', 'Tunai'), ('QRIS', 'QRIS'), ('TRANSFER', 'Transfer Bank'), ('AGGREGATOR', 'Aggregator (GoFood/GrabFood/ShopeeFood)'), ('OTHER', 'Lainnya')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('merchant_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='pos_config.merchantposconfig')),
                ('offset_coa_account', models.ForeignKey(blank=True, help_text='Akun debit saat pembayaran diterima (Kas, Bank, dll)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_payment_method_offset', to='master_data.akun')),
                ('payment_account', models.ForeignKey(blank=True, help_text='Akun kas/bank untuk metode ini. Override merchant default_payment_account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_payment_method_account', to='master_data.akun', verbose_name='Payment Account')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='pos_config.storeposconfig')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='pos_config.storeposconfig')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_logs', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_logs', to='pos_config.storeposconfig')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='pos_config.workshift')),
            ],
        ),
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500)),
                ('p256dh_key', models.CharField(max_length=200)),
                ('auth_key', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('CASHIER', 'Kasir'), ('KITCHEN', 'Dapur'), ('MANAGER', 'Manajer')], default='CASHIER', max_length=20)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='pos_config.storeposconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
