# Generated by Django 6.0.4 on 2026-05-07 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('pos_config', '0001_initial'),
        ('purchase', '0003_add_nilai_residu_to_item_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantposconfig',
            name='default_payment_account',
            field=models.ForeignKey(blank=True, help_text='Akun kas/piutang default jika PaymentMethod tidak punya payment_account sendiri.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_merchant_payment', to='master_data.akun', verbose_name='Default Payment Account'),
        ),
        migrations.AddField(
            model_name='merchantposconfig',
            name='offset_coa_account',
            field=models.ForeignKey(blank=True, help_text='Akun HPP — digunakan sebagai offset_coa_account di SalesItem.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_merchant_offset', to='master_data.akun', verbose_name='HPP Account'),
        ),
        migrations.AddField(
            model_name='merchantposconfig',
            name='sub_transaction_type',
            field=models.ForeignKey(blank=True, help_text='Sub-tipe transaksi penjualan POS (module=sales, direction=outflow).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_merchant_configs', to='purchase.subtransactiontype', verbose_name='Sub-Transaction Type'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='payment_account',
            field=models.ForeignKey(blank=True, help_text='Akun kas/bank untuk metode ini. Override merchant default_payment_account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_payment_method_account', to='master_data.akun', verbose_name='Payment Account'),
        ),
    ]
