# Generated by Django 6.0.4 on 2026-06-05 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitas_bisnis', '0002_is_company_profile'),
        ('master_data', '0001_initial'),
        ('pos_config', '0002_merchant_accounting_fields'),
        ('purchase', '0005_subtransactiontype_payment_term_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletPOSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Kosongkan = pakai default dari Store (lv2) atau Merchant (lv1).', max_digits=5, null=True, verbose_name='Tax % (Override)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_outlet_payment', to='master_data.akun', verbose_name='Payment Account (Override)')),
                ('entitas_bisnis_lv3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos_config', to='entitas_bisnis.entitasbisnislv3')),
                ('merchant_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='pos_config.merchantposconfig')),
                ('offset_coa_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_outlet_offset', to='master_data.akun', verbose_name='HPP Account (Override)')),
                ('revenue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_outlet_revenue', to='master_data.akun', verbose_name='Revenue Account (Override)')),
                ('sub_transaction_type', models.ForeignKey(blank=True, help_text='Kosongkan = pakai default dari Merchant (lv1).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_outlet_configs', to='purchase.subtransactiontype', verbose_name='Sub-Transaction Type (Override)')),
            ],
            options={
                'verbose_name': 'Outlet POS Config',
            },
        ),
    ]
