# Generated by Django 6.0.4 on 2026-06-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_config', '0003_outlet_pos_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletposconfig',
            name='qris_image',
            field=models.ImageField(blank=True, null=True, upload_to='pos/qris/', verbose_name='QRIS Image'),
        ),
        migrations.AlterField(
            model_name='outletposconfig',
            name='tax_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kosongkan = 0%.', max_digits=5, null=True, verbose_name='Tax %'),
        ),
    ]
