# Generated by Django 6.0.4 on 2026-04-16 14:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitas_bisnis', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsetLainnyaRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aset_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Nomor Aset')),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=15, verbose_name='Quantity')),
                ('harga_perolehan', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Harga Perolehan')),
                ('total_value', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=19, verbose_name='Nilai Perolehan')),
                ('akumulasi_amortisasi', models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Akumulasi Amortisasi')),
                ('tanggal_perolehan', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Tanggal Perolehan')),
                ('masa_manfaat', models.PositiveIntegerField(blank=True, help_text='Override masa manfaat dari item master. Kosongkan untuk menggunakan nilai item master.', null=True, verbose_name='Masa Manfaat (Tahun)')),
                ('metode_amortisasi', models.CharField(blank=True, choices=[('straight_line', 'Garis Lurus (Straight Line)'), ('declining_balance', 'Saldo Menurun (Declining Balance)'), ('units_of_production', 'Unit Produksi (Units of Production)'), ('revenue_based', 'Berbasis Pendapatan (Revenue Based)')], default='', help_text='Override metode amortisasi dari item master.', max_length=30, verbose_name='Metode Amortisasi')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entitas_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aset_lainnya_records', to='entitas_bisnis.entitasbisnis', verbose_name='Entitas Bisnis')),
                ('item', models.ForeignKey(limit_choices_to={'tipe_item': 'ALL'}, on_delete=django.db.models.deletion.PROTECT, related_name='aset_lainnya_records', to='purchase.itemmasterpurchase', verbose_name='Item Master')),
                ('purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aset_lainnya_records', to='purchase.purchaseitem', verbose_name='Purchase Item')),
            ],
            options={
                'verbose_name': 'Aset Lainnya Record',
                'verbose_name_plural': 'Aset Lainnya Records',
                'ordering': ['-tanggal_perolehan', '-created_at'],
                'indexes': [models.Index(fields=['item', 'tanggal_perolehan'], name='idx_alr_item_tanggal'), models.Index(fields=['entitas_bisnis', 'tanggal_perolehan'], name='idx_alr_eb_tanggal'), models.Index(fields=['aset_number'], name='idx_alr_number')],
            },
        ),
    ]
